### ISSUE TITLE
New route to binary @ swift.org 🎉

### ISSUE THREAD

**Issue by kimar** [kylef/swiftenv#10]
**Rationale**
```
$ swiftenv install swift-2.2-SNAPSHOT-2016-01-25-a
swift-2.2-SNAPSHOT-2016-01-25-a was not found on swift.org.
https://swift.org/builds/xcode/swift-2.2-SNAPSHOT-2016-01-25-a/swift-2.2-SNAPSHOT-2016-01-25-a-osx.pkg
```
**Old binary url**
```
https://swift.org/builds/xcode/swift-$VERSION/swift-$VERSION-osx.pkg
```

**New binary url**
```
https://swift.org/builds/swift-2.2-branch/xcode/swift-2.2-SNAPSHOT-2016-01-25-a/swift-2.2-SNAPSHOT-2016-01-25-a-osx.pkg
```

🙈

**Comment by kylef** [comment]
This is going to get complicated, I need to add logic to do development snapshots vs "branch" releases. I'll get to this soon, but for now I have made it possible to "swiftenv install <URL>" in master if you want to give this a try.

Also remember you can install it manually and swiftenv will pick it up.

**Comment by kimar** [comment]
Yeah I'd reckon things won't get less complicated once we're dealing with a stable release cycle and legacy/maintenance released etc. too. I actually thought about adding a flag e.g. `swiftenv install --url <url to pkg>` to go into manual override mode and skip the automated parsing. The regular `swiftenv install` command could then still try to parse and guess the url.

What could possibly go wrong?
Well I guess in the worst case a file's being downloaded which can be executed but is not an actual pkg. Maybe this could be caught  by using `file` command to check the `mime-type` of the downloaded file upfront executing?

Maybe also that's even too complicated but then again ¯\_(ツ)_/¯

**Comment by kimar** [comment]
Btw @kylef you sure you pushed to `master`?

**Comment by kylef** [comment]
@kimar Whoops, I think I forgot before I left. Unfortunately left my other Laptop which it was on for the weekend, will have to push this on Monday unfortunately.

**Comment by kimar** [comment]
@kylef no worries man, as the Ubuntu 14.04 Jan 25 snapshot of 2.2 lacks `swift-build` I can deploy on the server. That said I'm fine with continuing to use the Jan 11 build for the time being.
