### ISSUE TITLE
Swift 4.0 on macOS?

### ISSUE THREAD

**Issue by ryuichis** [kylef/swiftenv#100]
Swift 4.0 was finally released yesterday, and on macOS, it's part of the Xcode 9 without a pkg installer as development snapshots. By looking at this commit https://github.com/kylef/swiftenv-api/commit/12e7c76e0fda1f8fdd6edc47c5554f4174e2e1f5, I don't see it for macOS, which is understandable.

My question is, I have a `.swift-version` file, which is set to `4.0`, and it works in Linux environments. How should I set swiftenv up properly to use 4.0 on macOS? Thanks!

**Comment by kylef** [comment]
@ryuichis 4.0 should be found inside Xcode and be selected.

Are you seeing the same?

```
$ swiftenv versions --verbose
  4.0-DEVELOPMENT-SNAPSHOT-2017-08-21-a [from toolchain]
* 4.0 [from xcode /Users/kyle/Downloads/Xcode.app] (set by /Users/kyle/.swift-version)
```

**Comment by ryuichis** [comment]
Hmmm, thanks for your reply, but fortunately, I don't see the `4.0` entry. This is what I have

```
$ swiftenv versions --verbose
  4.0-DEVELOPMENT-SNAPSHOT-2017-09-16-a [from toolchain]
```

**Comment by kylef** [comment]
Could you check which version of Xcode is selected:

```shell
$ xcode-select -p
/Applications/Xcode-beta.app/Contents/Developer
```

Then which version of Swift inside that version of Xcode:

```shell
$ xcrun swift --version
Apple Swift version 4.0 (swiftlang-900.0.59 clang-900.0.34.2)
Target: x86_64-apple-macosx10.9
```

**Comment by ryuichis** [comment]
Not sure if it helps, but some additional information:

```
Ryuichis-MacBook-Pro:bin ryuichis$ ./swift --version
Apple Swift version 4.0 (swiftlang-900.0.65 clang-900.0.37)
Target: x86_64-apple-macosx10.9
Ryuichis-MacBook-Pro:bin ryuichis$ pwd
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
Ryuichis-MacBook-Pro:bin ryuichis$
```

**Comment by ryuichis** [comment]
```
Ryuichis-MacBook-Pro:bin ryuichis$ xcode-select -p
/Applications/Xcode.app/Contents/Developer
Ryuichis-MacBook-Pro:bin ryuichis$ xcrun swift --version
Apple Swift version 4.0 (swiftlang-900.0.65 clang-900.0.37)
Target: x86_64-apple-macosx10.9
Ryuichis-MacBook-Pro:bin ryuichis$ 
```

And I installed Xcode from Mac App Store this morning.

**Comment by kylef** [comment]
swiftenv uses Spotlight to find all of the Xcode builds, I wonder if this could be some spotlight indexing problem, can you run the following to see if your Xcode is listed:

```
$ mdfind "kMDItemCFBundleIdentifier == 'com.apple.dt.Xcode'"
/Users/kyle/Downloads/Xcode.app
/Applications/Xcode.app
/Applications/Xcode-beta.app
```

**Comment by ryuichis** [comment]
Knowing swiftenv uses Spotlight is very helpful, and you are right, spotlight indexing is the culprit of my issue. Forcing Spotlight to refresh solved my problem. Thanks @kylef!

**Comment by leo150** [comment]
In my case `swiftenv install --list` caused some misconceptions:
```
$ swiftenv install --list
2.2-dev
2.2
2.2.1
3.0-dev
3.0
3.0.1
3.0.2
3.1-dev
3.1
3.1.1
4.0-dev
```
However, `swiftenv install 4.0` works fine and downloads release version.

**Comment by kylef** [comment]
@leo150 `swiftenv install --list` currently only shows the versions that swiftenv knows how to build. However when `swiftenv install` encounters an unknown version of Swift it will query if there is an available binary for the current platform.
