### ISSUE TITLE
swiftenv global not rewrite .swift-version file

### ISSUE THREAD

**Issue by SiegeLeo** [kylef/swiftenv#104]
i have installed Xcode 9.0, and swift 3.1.1
when i use `swiftenv global 3.1.1`.   
and use `swiftenv global`, the terminal output `3.1.1`.
then use `swift --version` output `swift 4.0`
i check the `.swift-version` file always show `swift 4.0`
then I modified the file to `swift 3.1.1`, the `swift --version` output correct.

**Comment by kylef** [comment]
@SiegeLeo Please see the documentation regarding global and local:

- https://swiftenv.fuller.li/en/latest/commands.html#local

> ## Global
> Sets the global version of Swift to be used by writing to the ~/.swiftenv/version file. This version can be overridden by application-specific .swift-version file, or by setting the SWIFT_VERSION environment variable.
> ## Local
> Sets the local application-specific Swift version by writing the version to a .swift-version file in the current directory. This version overrides the global version and can also be overridden further by the SWIFT_VERSION environment variable.

**Comment by SiegeLeo** [comment]
it means the global setting was overridern by setting the SWIFT_VERSION environment variable ？ so, how can i resolved this problem

**Comment by SDGGiesbrecht** [comment]
你好, @SiegeLeo 

`$ swiftenv global` i.e. `~/.swiftenv/version`
↳ overridden by `$ swiftenv local` i.e. `[working directory]/.swift-version`
&nbsp;&nbsp;&nbsp;&nbsp;↳ overridden by `SWIFT_VERSION`

***

∴ when you started (在开始):

? (`~/.swiftenv/version`)
↳ overridden by 4.0 (`[working directory]/.swift-version`)
&nbsp;&nbsp;&nbsp;&nbsp;↳ ~~∅, no override (`SWIFT_VERSION`)~~
= 4.0

***

Then you did (之后, 你做了):

```shell
$ swiftenv global 3.1.1
```

3.1.1 (`~/.swiftenv/version`) **← This changed. (这改变了)**
↳ overridden by 4.0 (`[working directory]/.swift-version`)
&nbsp;&nbsp;&nbsp;&nbsp;↳ ~~∅, no override (`SWIFT_VERSION`)~~
= 4.0

***

Then you did (之后, 你做了):

`.swift‐version` → 3.1.1

3.1.1 (`~/.swiftenv/version`)
↳ overridden by 3.1.1 (`[working directory]/.swift-version`) **← This changed. (这改变了)**
&nbsp;&nbsp;&nbsp;&nbsp;↳ ~~∅, no override (`SWIFT_VERSION`)~~
= 3.1.1

***

So, if you want 3.1.1 everywhere, and you want to undo all possible overrides (解):

```shell
$ swiftenv global 3.1.1
$ swiftenv local --unset
$ unset SWIFT_VERSION
```

3.1.1 (`~/.swiftenv/version`) **← This changed. (这改变了)**
↳ ~~∅, no override (`[working directory]/.swift-version`)~~ **← This changed. (这改变了)**
&nbsp;&nbsp;&nbsp;&nbsp;↳ ~~∅, no override (`SWIFT_VERSION`)~~ **← This changed. (这改变了)**
= 3.1.1

**Comment by kylef** [comment]
@SiegeLeo You set a global version but you have a local override. You mentioned you had a `.swift-version` file that is locally overriding the global version. You can run `swiftenv local --unset` to unset the local version so global version will be used:

```shell
$ swiftenv version
4.0 (set by /Users/kyle/.swift-version)

$ swiftenv local 
4.0

$ swiftenv local --unset

$ swiftenv version
4.0.2 (set by /Users/kyle/.swiftenv/version)
```
