### ISSUE TITLE
Unable to install swift 4.0-dev on ubuntu 16.04

### ISSUE THREAD

**Issue by cbarrerah** [kylef/swiftenv#107]
Hi,

I was able to install correctly 3.1 and 4.0, but when trying to install 4.0-dev for a fix i finde the following messages

Found swift, skipping download
Found llvm, skipping download
Found clang, skipping download
Found lldb, skipping download
Found cmark, skipping download
Found llbuild, skipping download
Found swiftpm, skipping download
Found compiler-rt, skipping download
Found swift-corelibs-xctest, skipping download
Found swift-corelibs-foundation, skipping download
Found swift-corelibs-libdispatch, skipping download
Building Swift
This may take a very long time...
Building Swift failed
Check out the logfile for more information: /home/username/.swiftenv/tmp/swiftenv-build-4.0-dev/swiftenv-build.20171121204213.104505.log
You can inspect or delete the working tree at: /home/username/.swiftenv/tmp/swiftenv-build-4.0-dev

When inspecting the log, i found:
/usr/bin/env: 'python\r' : No such file or directory

Which may point to some kind of trouble finding python:
which python says:
/usr/bin/python

and /usr/bin is in my $PATH, so i'm a little lost, any ideas?

Thanks in advance

**Comment by kylef** [comment]
Strange `/usr/bin/env: 'python\r' : No such file or directory` there seems to be a carriage return or some characters after the `python` (`python\r`).

Could you please share your `.gitconfig` file? I wonder if you have some of the `autocrlf` options enabled that could cause these `\r` to be added to the checkout.
