### ISSUE TITLE
Unable to install other versions of swift

### ISSUE THREAD

**Issue by theRahim** [kylef/swiftenv#109]
I just install swiftenv flowing the instruction using GIT. Then I run some commands are:
swiftenv version
swiftenv versions
swiftenv install --list
It's working well, But when I am run this command to install a version of Swift it show me this error.
Commands are : swiftenv install 3.0, swiftenv install 3.1.1
Error: There was a problem checking for a binary release of 3.0, server returned 403.

**Comment by kylef** [comment]
Not entirely sure why that may be. I'm guessing it would be a temporary problem as I am not able to get the server to return a 403 and only 200 or 404.

As of more recent versions of swiftenv, we will now include a cache of the latest major releases to prevent any problems on the server side from effecting installation.
