### ISSUE TITLE
Easier way to install swiftenv on Ubuntu (apt-get)

### ISSUE THREAD

**Issue by czechboy0** [kylef/swiftenv#11]
Would be a nice-to-have, I now use swiftenv everywhere and being able to install it from apt-get would be :+1: .

**Comment by kylef** [comment]
From what I understand, this would be out of my control. It's up to Ubuntu / distro package maintainers to add it.

**Comment by czechboy0** [comment]
Didn't know that, ok then :)

**Comment by BlueT** [comment]
A good way to achieve this is to make a Ubuntu PPA https://launchpad.net/ubuntu/+ppas :-)

**Comment by kylef** [comment]
@BlueT Do you have much experience with this? I can't find any documentation.

Would be great to know if this can be achieved during release via Travis CI.
