### ISSUE TITLE
.swift-version conflicting with Cocoapods

### ISSUE THREAD

**Issue by abl** [kylef/swiftenv#110]
It looks like a number of projects that are both Cocoapods and Swift packages (e.g. [SwiftLint](https://github.com/realm/SwiftLint)) are specifying a Swift version of 3.2. Since Swift 3.2 doesn't exist as a release - it's the Swift 3 compatibility mode of the toolchain shipping in Xcode 9 / Swift 4.0 - attempts to `swift build` fail.

If you require Swift 3.2, you're really requiring the Swift 4.0 toolchain, and I saw two ways to solve this:

1) A lightweight map maintained in swiftenv that maps Swift versions, when needed, to the toolchain release version that contains that version.

2) A user override map that does the same; for example, I might rely on some fixes in a snapshot between 4.0 and 4.1, and I want my team to all have the same version, so I'd have them add a configuration entry like `"4.0": "DEVELOPMENT-SNAPSHOT-2018-01-25-a"`. (`"3.2": "4.0"` would be a default entry; lookup would recurse until a cycle is hit or the chain is fully resolved; etc.)

By the time that you're doing something like this you're probably comfortable telling everyone to set `SWIFTENV_VERSION` globally, of course, so I'm leaning towards the first, simplest, solution.

Happy to submit a PR if you like the concept!

**Comment by ikesyo** [comment]
As of CocoaPods 1.4.0 `.swift-version` is a deprecated way to specify the supported Swift version, so this will not be a problem anymore I think.

**Comment by kylef** [comment]
https://github.com/CocoaPods/CocoaPods/issues/7436#issuecomment-366295334 will solve the problem in CocoaPods.

If you are developing a library, it's likely you would want to support more than a single version of Swift for example 4.0, 4.0.2, 4.0.3 in the same code base. I personally would only commit and save a `.swift-version` in applications and tools where it is developed, tested and shipped for a single version of swift. You can temporally create a `.swift-version` file if you want to override the version from the system default and remove it to work around CocoaPods problems. You can also use [direnv](https://github.com/direnv/direnv) or autoenv to source `SWIFT_VERSION` into your environment to configure the swift env in a separate file if desired.
