### ISSUE TITLE
Not able to use swiftenv on mac OS 10.12.6

### ISSUE THREAD

**Issue by harry329** [kylef/swiftenv#113]
When I am running any swiftenv command I am getting following error - 
$ swiftenv versions
Unknown command `/usr/local/bin/swiftenv'. Please specify one command of: add-blob, alias-env, attach-disk, blobs, cancel-task......

I tried reinstalling swiftenv using both git and brew but nothing works.

**Comment by kylef** [comment]
Seems like an installation problem, which shell are you using?

Could you try launching a new terminal after installing to see if it would be a recognised command in the new shell instance (some shells have aggressive PATH cache iirc).
