### ISSUE TITLE
Installation fails on Ubuntu 17.0

### ISSUE THREAD

**Issue by Nedra1998** [kylef/swiftenv#115]
After running `swiftenv install 4.0`, it runs and downloads all the files and attempts the install. But after a while it fails. The log files only says
```
.pyenv/libexec/pyenv-exec: line 47: /home/arden/.swiftenv/tmp/swiftenv-build-4.0/bin/python: Argument list too long
```

**Comment by kylef** [comment]
Looks like the error is coming from pyenv saying that the arguments list for Python is too long. Can you confirm that your pyenv setup is working correctly?

**Comment by Nedra1998** [comment]
Temporarily removing pyenv seems to have resolved the issue. Thanks

**Comment by BigSully** [comment]
> Temporarily removing pyenv seems to have resolved the issue. Thanks

```
export PATH="/home/kk/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```
Comment out or simple remove those pyenv initialization script like the above code in `~/.bashrc` or in  `~/.profile`
