### ISSUE TITLE
Thinking of a possible SourceKitten integration for Linux

### ISSUE THREAD

**Issue by felix91gr** [kylef/swiftenv#117]
Hi!

You may know [SourceKitten](https://github.com/jpsim/SourceKitten). It's a framework and command line tool that allows interaction with SourceKit. This has made possible tools like [SwiftLint](https://github.com/realm/SwiftLint) and [SourceKittenDaemon](https://github.com/terhechte/SourceKittenDaemon). For usage within Linux, the [only requirement](https://github.com/jpsim/SourceKitten#installation
) is that the environment variable `LINUX_SOURCEKIT_LIB_PATH` is set to
`$SWIFT_BINARIES_HOME/usr/lib/`. Do you think **swiftenv** could provide integration with this?

**Any help you'd need I can provide**. It's very important for me that something as important as `SourceKit` is accessible within Linux, because it will allow users to have IDEs with autocompletion and linting.

Please tell me if this is possible.
-- Félix

**Comment by felix91gr** [comment]
I mean, I'm almost certain it is possible. But what I think I want to ask if there's interest in providing this, because you have my hands if you need'em

**Comment by SDGGiesbrecht** [comment]
@felix91gr, I would also very much like to use them together too.

I tried for a while to accomplish it from the SourceKitten side (jpsim/SourceKitten#433), but even pointing in the right place did not work because the aliasing inherent to swiftenv’s design interfered with the dynamic linker (or possibly SourceKit’s own linking expectations underneath). At the time at least, I was forced to give up and treat the two tools as mutually exclusive.

Either tool (or even Swift itself) may have evolved since then so that they are now compatible. A pull request that solves it would likely be very welcome at SourceKitten. But I do think it is more SourceKitten’s responsibility to do a better job of finding Swift, and that this does not really belong to swiftenv’s domain.

**Comment by kylef** [comment]
I haven't played much with SourceKit myself on Linux, but happy to see how we can make it easier to use with swiftenv. I'm guessing you should be able to set `LINUX_SOURCEKIT_LIB_PATH` to the swift lib path for the respective Swift version you want to use. 

This would be `../../lib` relative to the swift binary, so using the following could work:

```shell
$ swiftenv which swift
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift
```

```shell
$ set -x LINUX_SOURCEKIT_LIB_PATH /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib
```

The downside is that if you change the swift version globally, locally etc the `LINUX_SOURCEKIT_LIB_PATH` wouldn't update correctly, but at least this should be a good start to see if that works and then we can figure out how to make the rest work.

I don't think it will work with swiftenv built swift as I don't think source kit is built or even installed, it may work with the official provided binaries if they include source kit (not sure if they do).

**Comment by felix91gr** [comment]
Hi all!
Well I was planning on answering differently than this... but JP Simard took me by surprise on twitter with the [new SourceKitten release](https://github.com/jpsim/SourceKitten/releases/tag/0.20.0). 

`swiftenv` is now supported on Linux. Holy shit.
![image](https://user-images.githubusercontent.com/11747623/38463760-fb3e27b6-3ad7-11e8-8a6c-75d8b2f7541d.png)

Tomorrow I can't test this, but I will next Monday. I hope it works as it says in the tin. omg.

**Comment by felix91gr** [comment]
[Here's the sourcecode on the PR that changed the search strategy](https://github.com/jpsim/SourceKitten/commit/10bf54d2b7c0ffbd799ed1e8b7c9b59bcb20257c). It looks real, really real. My god.

**Comment by felix91gr** [comment]
I tested it. It's real. It works really really well. Thanks for the discussion, y'all :)

**Comment by SDGGiesbrecht** [comment]
Thanks for noticing it, @felix91gr. I will definitely be putting it to use too.
