### ISSUE TITLE
Autocompletion for swiftenv install

### ISSUE THREAD

**Issue by rbukovansky** [kylef/swiftenv#119]
Hi,
when I try autocompletion of `swiftenv install` I do get just possible release versions to install, but no parameters like you can get for i.e. `swiftenv init`. Could you please take a look?

Thank you.

**Comment by kylef** [comment]
That's a good point, I've took a go at implementing this in https://github.com/kylef/swiftenv/pull/120. @rbukovansky would you like to give that a go and make sure I didn't miss anything.

**Comment by rbukovansky** [comment]
@kylef I have made review for #120.

**Comment by rbukovansky** [comment]
@kylef https://github.com/kylef/swiftenv/commit/f16de78c5e6b7188df1ea21cc60d9586f4913a1a looks and works good! Thank you!
