### ISSUE TITLE
CI solution for building Swift Toolchain

### ISSUE THREAD

**Issue by DenHeadless** [kylef/swiftenv#12]
Hey! 

I tried using your [gist](https://gist.github.com/kylef/5c0475ff02b7c7671d2a) for building Swift OSS snapshot and running SPM on Travis CI, however it does not seem to work on latest version of Swift. Is it updated to latest swift.org URLs? 

Here's successful build with old version of Swift - https://travis-ci.org/DenHeadless/Transporter/jobs/109139150
And here's attempt for building with new one - https://travis-ci.org/DenHeadless/Transporter/jobs/109138678

I will keep digging this myself, but any help from you would be much appreciated.

**Comment by DenHeadless** [comment]
Ok, so it seems like i was able to install latest version of Swift, however it does not include SPM. For anyone interested, i created separate build script

```bash
#!/usr/bin/env bash

set -e

git clone --depth 1 https://github.com/kylef/swiftenv.git ~/.swiftenv

echo 'export SWIFTENV_ROOT="$HOME/.swiftenv"' > "$HOME/.swiftenv/init"
echo 'export PATH="$SWIFTENV_ROOT/bin:$PATH"' >> "$HOME/.swiftenv/init"
echo 'eval "$(swiftenv init -)"' >> "$HOME/.swiftenv/init"

if [ -f ".swift-version" ] || [ -n "$SWIFTENV_VERSION" ]; then
  export SWIFTENV_ROOT="$HOME/.swiftenv"
  export PATH="$SWIFTENV_ROOT/bin:$PATH"
  eval $(swiftenv init -)
fi
```

that is executed from Makefile using sh. However running 

```bash
. ~/.swiftenv/init && swift build
```

Prints:

```bash
<unknown>:0: error: no such file or directory: 'build'
```

Which simply implies, that SPM is not installed. Probably it's too early to use Swift Package Manager in CI builds.

**Comment by kylef** [comment]
Yes, you're installing version `2.2-SNAPSHOT-2015-12-22-a` which doesn't include SPM. You probably want to use the development snapshots such as `DEVELOPMENT-SNAPSHOT-2016-01-25-a` which does include SPM.

Check the [2.2 release notes](https://swift.org/blog/swift-2-2-release-process/) for more information as to why it doesn't include SPM:

> Swift on Linux will be included in this release. However it is still relatively new and has known caveats. Swift 2.2 will not include the Swift Core Libraries but will include LLDB and the REPL.

> The Swift Package Manager is still early in development and will not be included in this release.
