### ISSUE TITLE
Can't launch REPL after installing 3.3.1

### ISSUE THREAD

**Issue by peterlobster** [kylef/swiftenv#123]
Hi, I'm pretty new at Swift and installed swiftenv to start playing around with it. I followed the instructions on the website to install 3.1.1, however every time I try `swift -v`, I get the follow issue.

```
$ swift -v
Apple Swift version 3.1 (swift-3.1.1-RELEASE)
Target: x86_64-apple-macosx10.9
/Library/Developer/Toolchains/swift-3.1.1-RELEASE.xctoolchain/usr/bin/lldb "--repl=-enable-objc-interop -sdk /Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk -color-diagnostics"
error: failed to launch REPL process: process launch failed: unable to locate debugserver
```

**Comment by kylef** [comment]
That is odd, could I just confirm if you have installed Swift 3.1.1 via swiftenv install or if you installed the pkg toolchain from swift.org?

- Which version of macOS are you running?
- Do you have Xcode installed or the Xcode command line tools? (I am not sure if this will make any difference but maybe we can identify how your system differs from mine and what the underlying problem may be).
- What is the output of `which swift`?
- What is the output of `swiftenv which swift`?

I've tried to reproduce but the following is working for me on High Sierra.

```shell
$ swiftenv install 3.1.1
...
3.1.1 has been installed.


$ swift -v
Apple Swift version 3.1 (swift-3.1.1-RELEASE)
Target: x86_64-apple-macosx10.9
/Library/Developer/Toolchains/swift-3.1.1-RELEASE.xctoolchain/usr/bin/lldb "--repl=-enable-objc-interop -sdk \"/Users/kyle/Downloads/Xcode-beta 3.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk\" -color-diagnostics"
Welcome to Apple Swift version 3.1 (swift-3.1.1-RELEASE). Type :help for assistance.
  1>  
```

**Comment by peterlobster** [comment]
Hey Kyle,

Thanks for getting back to me.

I'm using 10.13.4.

I have both Xcode Command Line Tools and Xcode installed. My Xcode is Version 9.3 (9E145).

I can run the REPL on 4.1 which is the system default.

I also have cmake and ninja if it makes a difference.

Here's the outputs you asked for running 3.1.1
$ swift --version
Apple Swift version 3.1 (swift-3.1.1-RELEASE)
Target: x86_64-apple-macosx10.9

$ which swift
/Users/peter/.swiftenv/shims/swift

$ swiftenv which swift
/Library/Developer/Toolchains/swift-3.1.1-RELEASE.xctoolchain/usr/bin/swift

Here's the outputs you asked for running 4.1 system default
$ swift --version
Apple Swift version 4.1 (swiftlang-902.0.48 clang-902.0.37.1)
Target: x86_64-apple-darwin17.5.0

$ which swift
/Users/peter/.swiftenv/shims/swift

$ swiftenv which swift
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift

**Comment by peterlobster** [comment]
@kylef Have you had a change to look over that output?

**Comment by peterlobster** [comment]
@kylef I've tried uninstalled 3.1.1 and I get this output...
```
$ swiftenv uninstall 3.1.1
3.1.1 is not installed.
```

If I run LLDB on 3.1.1 it runs, here' the output of LLDB -v
```
(lldb) v
lldb-360.0.0 (buildbot 2017-04-21)
  Swift-3.1 (revision 6067e30b9034ab735bfb6996cce8dba80699ab37)
  clang revision f38438fc0161d13f2deb8b1cfb201af562692364
```

Does that help any?

**Comment by peterlobster** [comment]
@kylef It's all good! I hope I helped in some way.

**Comment by kylef** [comment]
I accidentally discovered how this is possible while trying to build an unrelated project on another machine:

```shell
$ ./configure
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcrun: error: unable to lookup item 'PlatformPath' from command line tools installation
xcrun: error: unable to lookup item 'PlatformPath' in SDK '/'
```

Which led me to discover that xcodebuild will not work with CLI tools set as the selected path and subsequently swift requires Xcode selected too.

```shell
$ xcode-select  -p
/Library/Developer/CommandLineTools

$ xcodebuild
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

$ swift -v
Apple Swift version 4.0.3 (swift-4.0.3-RELEASE)
Target: x86_64-apple-macosx10.9
/Library/Developer/Toolchains/swift-4.0.3-RELEASE.xctoolchain/usr/bin/lldb "--repl=-enable-objc-interop -sdk /Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk -color-diagnostics"
error: failed to launch REPL process: process launch failed: unable to locate debugserver
```

So to reproduce you can use the following:

```
$ sudo xcode-select -s /Library/Developer/CommandLineTools
```

Likely while invoking swift via swiftenv we could detect the Xcode path is CommandLineTools and present an appropriate error to the user. I noticed on https://swift.org/download/#requirements-for-tools it declares the versions of Xcode which are required for certain versions of Swift. Perhaps this check can be made so a user doesn't hit any other problems such as if they tried to use Swift 4 with Xcode 8.

**Comment by peterlobster** [comment]
@kylef Interesting. I was in the the process of reporting a related problem...
