### ISSUE TITLE
Install script has moved to /en/latest/install.sh

### ISSUE THREAD

**Issue by NobodyNada** [kylef/swiftenv#125]
As of this morning, every request to [https://swiftenv.fuller.li/install.sh](https://swiftenv.fuller.li/install.sh) seems to be failing with a 500 error, causing my CI builds to fail.  [https://swiftenv.fuller.li/en/latest/install.sh](https://swiftenv.fuller.li/en/latest/install.sh) seems to work.  Is this move intentional?

**Comment by kylef** [comment]
Certainly not intentional. It appears to be a problem with readthedocs. I'm trying to figure out what caused this.

**Comment by kylef** [comment]
Looks like it was a bug introduced in readthedocs that will be fixed by https://github.com/rtfd/readthedocs.org/pull/3965

**Comment by mxcl** [comment]
Seems to be available again.
