### ISSUE TITLE
Build Swift 2.2.1 Fail

### ISSUE THREAD

**Issue by peterlobster** [kylef/swiftenv#126]
```
$ swiftenv install 2.2.1
Downloading swift (swift-2.2.1-RELEASE)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   132    0   132    0     0    371      0 --:--:-- --:--:-- --:--:--   371
100 8245k    0 8245k    0     0  3806k      0 --:--:--  0:00:02 --:--:-- 6934k
Downloading swift-llvm (swift-2.2.1-RELEASE)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   137    0   137    0     0    419      0 --:--:-- --:--:-- --:--:--   420
100 21.5M    0 21.5M    0     0  4424k      0 --:--:--  0:00:04 --:--:-- 5977k
Downloading swift-clang (swift-2.2.1-RELEASE)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   138    0   138    0     0    430      0 --:--:-- --:--:-- --:--:--   429
100 12.3M    0 12.3M    0     0  4184k      0 --:--:--  0:00:03 --:--:-- 6868k
Downloading swift-lldb (swift-2.2.1-RELEASE)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   137    0   137    0     0    412      0 --:--:-- --:--:-- --:--:--   413
100 13.5M    0 13.5M    0     0  4432k      0 --:--:--  0:00:03 --:--:-- 6802k
Downloading swift-cmark (swift-2.2.1-RELEASE)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   138    0   138    0     0    425      0 --:--:-- --:--:-- --:--:--   425
100  209k    0  209k    0     0   146k      0 --:--:--  0:00:01 --:--:--  319k
Building Swift
This may take a very long time...
Building Swift failed
Check out the logfile for more information: [/usr/local/var/swiftenv/tmp/swiftenv-build-2.2.1/swiftenv-build.20180419150546.6911.log](https://paste.ee/p/8Zm6E#section0)
You can inspect or delete the working tree at:[ /usr/local/var/swiftenv/tmp/swiftenv-build-2.2.1](https://paste.ee/p/8Zm6E#section1)
```

https://paste.ee/p/8Zm6E - For the logs

Building 2.2.1 fails. I have ninja and cmake both installed...

I believe the problem is related to not having Xcode 7 installed. I was thinking of installing Xcode 7 and using xcode-select...or I also found [xcode-install](https://github.com/KrauseFx/xcode-install) but it seems to have several problems that I dunno I want to deal.

I would appreciate any feedback...

**Comment by kylef** [comment]
Swift 2.2.1 has some very specific Xcode requirements, there's an open issue (https://github.com/kylef/swiftenv/issues/103) with the same problem so let's move over there.

Check out the [last comment](https://github.com/kylef/swiftenv/issues/103#issuecomment-345565908):

> Slava suggested installing an older Xcode. I have 7.3.1 under a different name, so I switched the Tools (using xcode-select), and it still didn't work. Then I noticed in the log that it wasn't using xcrun; instead the script is using the default Tools location. So, I renamed my current Xcode.app, renamed my copy of Xcode 7.3.1 to Xcode.app, and tried again. The build worked, then, and I was able to install v2.2.1 successfully.

I'd install Xcode 7.3.1 and give that a go, you might hit same problem as leanne63 did so you may need to fiddle with Xcode to select the correct one.

**Comment by peterlobster** [comment]
@kylef good looking out! I forgot to look for closed issues! Thanks.
