### ISSUE TITLE
Trouble Connecting to swiftenv-api.fuller.li

### ISSUE THREAD

**Issue by Redoubts** [kylef/swiftenv#127]
Don't know if anyone else is seeing this, but I'm reliably seeing SSL errors when trying to connect to the api endpoint. In particular, something like

`curl -v -o /dev/null --silent --head --write-out '%{http_code}'  https://swiftenv-api.fuller.li/versions/4.1.1/binaries/ubuntu14.04`

Will fail with an SSL error.

I'll see
`* SSL read: error:00000000:lib(0):func(0):reason(0), errno 104`
if I force tls1.1
`* curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to swiftenv-api.fuller.li:443`

Not sure why, but version 4.1.1 is much more unreliable than version 4.1 in this query.

**Comment by Redoubts** [comment]
As an additional failure mode, I may also see a hang:

```
* Added swiftenv-api.fuller.li:443:104.28.14.57 to DNS cache
* Hostname swiftenv-api.fuller.li was found in DNS cache
*   Trying 104.28.14.57...
* TCP_NODELAY set
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:14 --:--:--     0* Connection failed
* connect to 104.28.14.57 port 443 failed: Operation timed out
* Failed to connect to swiftenv-api.fuller.li port 443: Operation timed out
* Closing connection 0
curl: (7) Failed to connect to swiftenv-api.fuller.li port 443: Operation timed out
```

**Comment by kylef** [comment]
Hi, could you please share some information about your platform and version. Along with information about curl (`curl --version` output) and OpenSSL (`openssl ` output). This should help either reproducing or determining the underlying cause.
