### ISSUE TITLE
swift-build missing dependencies

### ISSUE THREAD

**Issue by Jerrot** [kylef/swiftenv#137]
Hi, 
I installed a binary snapshot on Ubuntu 18.04 using 
`swiftenv install https://swift.org/builds/development/ubuntu1804/swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a/swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04.tar.gz`

Swift itself runs fine, however I'm not able to use the Swift package manager, calling "swift-build" immediately fails with:
`swift-build: error while loading shared libraries: libBlocksRuntime.so.0: cannot open shared object file: No such file or directory`

Any help is appreciated, thanks!

**Comment by piotte13** [comment]
Exact same issue here. With DEVELOPMENT-SNAPSHOT-2018-09-10.

**Comment by kylef** [comment]
There is no such shared library (`libBlocksRuntime.so.0`) in the swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a tarball for Ubuntu 18.04. Which is either a bug on Apple side or a missing local dependency. Do you have all of the dependencies that Swift installation requires? https://swift.org/download/#installation-1 mentions that the `clang` and `libicu-dev`. I am not sure if the clang package contains libBlocksRuntime. If it does not then I think the best bet would be to reach out to the Swift team using their mailing list, the problem seems to be unrelated to swiftenv.

```
$ wget https://swift.org/builds/development/ubuntu1804/swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a/swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04.tar.gz
$ tar xvf swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04.tar.gz
$ find . -name '*.so'
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/liblldbIntelFeatures.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/libsourcekitdInProc.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/liblldb.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/lldb/clang/lib/linux/libclang_rt.scudo-x86_64.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/lldb/clang/lib/linux/libclang_rt.scudo_minimal-x86_64.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/lldb/clang/lib/linux/libclang_rt.ubsan_standalone-x86_64.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/lldb/clang/lib/linux/libclang_rt.hwasan-x86_64.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/lldb/clang/lib/linux/libclang_rt.ubsan_minimal-x86_64.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/lldb/clang/lib/linux/libclang_rt.dyndd-x86_64.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/lldb/clang/lib/linux/libclang_rt.asan-x86_64.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/swift/pm/llbuild/libllbuildSwift.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/swift/pm/llbuild/libllbuild.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/swift/pm/4_2/libPackageDescription.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/swift/pm/4/libPackageDescription.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/swift/clang/lib/linux/libclang_rt.scudo-x86_64.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/swift/clang/lib/linux/libclang_rt.scudo_minimal-x86_64.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/swift/clang/lib/linux/libclang_rt.ubsan_standalone-x86_64.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/swift/clang/lib/linux/libclang_rt.hwasan-x86_64.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/swift/clang/lib/linux/libclang_rt.ubsan_minimal-x86_64.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/swift/clang/lib/linux/libclang_rt.dyndd-x86_64.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/swift/clang/lib/linux/libclang_rt.asan-x86_64.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/swift/linux/libFoundation.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/swift/linux/libswiftGlibc.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/swift/linux/libdispatch.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/swift/linux/libXCTest.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/swift/linux/libswiftCore.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/swift/linux/libswiftSwiftOnoneSupport.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/swift/linux/libswiftRemoteMirror.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/python2.7/site-packages/lldb/_lldb.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/python2.7/site-packages/readline.so
./swift-DEVELOPMENT-SNAPSHOT-2018-08-26-a-ubuntu18.04/usr/lib/libswiftDemangle.so
```

**Comment by Jerrot** [comment]
Thanks for looking into and pushing me to the right direction. 
I can confirm this is not a swiftenv issue. I followed the requirements on the page you also linked, however the mention clang and libicu-dev are  are not enough.
However on the official swift repository on GitHub, you will find these lines:

> **Linux**
> 
> For Ubuntu, you'll need the following development dependencies:
> 
> `sudo apt-get install git cmake ninja-build clang python uuid-dev libicu-dev icu-devtools libbsd-dev libedit-dev libxml2-dev libsqlite3-dev swig libpython-dev libncurses5-dev pkg-config libblocksruntime-dev libcurl4-openssl-dev systemtap-sdt-dev tzdata rsync`

Note this also includes installing libblocksruntime(-dev) which fixes the reported issue.

**Comment by kylef** [comment]
Ah interesting. Those are dependencies listed in the README are for building Swift. I guess the list on the Swift website are perhaps outdated. Or perhaps this dependency is only new in the current snapshots and will be updated before the final release.
