### ISSUE TITLE
Is it possible to install on osx without sudo

### ISSUE THREAD

**Issue by mbroadst** [kylef/swiftenv#150]
It appears that `swiftenv` on OSX requires sudo, and installs the package to `/` by default (if I'm reading [this](https://github.com/kylef/swiftenv/blob/master/libexec/swiftenv-install#L144) correctly). Is there any way around this requirements? Our CI unfortunately does not jail its builds, so playing with the root directory (and using sudo in general) is not permitted. Is it as simple as adding a command line flag to install to particular path? I had thought they would be installed to `$SWIFTENV_ROOT/versions`, but I think that's only on linux.

**Comment by keith** [comment]
Technically the `installer` CLI requires root, regardless of where they are installed. In theory you could manually extract the contents of the pkg instead (like how the linux install with a `.tar.gz` works) assuming they don't have any custom install scripts. That way you could move it wherever you wanted.
