### ISSUE TITLE
Don't work on Travis CI and Linux

### ISSUE THREAD

**Issue by artemnovichkov** [kylef/swiftenv#155]
Here is my config:
```
os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode10.2
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - swift build
```
And [here](https://travis-ci.org/artemnovichkov/Carting/jobs/524090956) is my failed job log:
```
The program 'swift' is currently not installed. To run 'swift' please ask your administrator to install the package 'python-swiftclient'
```

**Comment by kylef** [comment]
@artemnovichkov Looking at the linked job / repository, I don't think you've set any Swift version to install and thus swiftenv will not install Swift.

You can add something like the following to your Travis CI configuration:

```yaml
env:
  - SWIFT_VERSION=5.0
```

**Comment by artemnovichkov** [comment]
It works, thanks! I guess it should be added to [Travis CI](https://swiftenv.fuller.li/en/latest/integrations/travis-ci.html) integration.

**Comment by dyna-dot** [comment]
Yeah downloading 5.0.1 now
