### ISSUE TITLE
`swiftenv install --list` doesn't list new releases

### ISSUE THREAD

**Issue by honghaoz** [kylef/swiftenv#156]
Swift 5.0.1 has been released for a long time ago (Apr 18, 2019)
However, when I run
```
$ swiftenv install --list                                              
2.2-dev
2.2
2.2.1
3.0-dev
3.0
3.0.1
3.0.2
3.1-dev
3.1
3.1.1
4.0-dev
4.0
4.0.2
4.0.3
4.1-dev
4.1
4.2-dev
5.0-dev
```
It doesn't list the latest Swift versions.

I'm able to install by running `swiftenv install 5.0.1`, however, it's will be convenient if the list functionality works.

**Comment by kylef** [comment]
`swiftenv install --list` only shows versions of Swift it is capable of building. Given the complexities of building Swift and the amount of resources required to do so, these are unmaintained.

You can pass `--no-build` to see all the versions that you can install without building (binary releases available for your platform):

```
$ ./bin/swiftenv install --list --no-build
3.0
3.0.1
3.0.2
3.1
3.1.1
4.0
4.0.2
4.0.3
4.1
4.1.1
4.1.2
4.1.3
4.2
4.2.1
4.2.2
4.2.3
4.2.4
5.0
5.0.1
```

**Comment by kylef** [comment]
Good to mention, `--list --no-build` is also only capable of showing versions that the installed version of swiftenv is aware of too, it is expected to return immediately (and used for tab completions) so hitting APIs isn't a good experiance.

In those kind of cases, `swiftenv install` may succeed for a version that the installed swiftenv doesn't locally know about.

**Comment by honghaoz** [comment]
Thanks for the great explanations! Appreciated!
