### ISSUE TITLE
Travis CI issue with 5.0.1

### ISSUE THREAD

**Issue by bwetherfield** [kylef/swiftenv#158]
Installing Swift 5.0.1 within Travis CI using swiftenv, I run into the following error when I build and run my tests:
```
swift: /home/buildnode/jenkins/workspace/oss-swift-5.0-package-linux-ubuntu-14_04/swift/lib/SIL/SILVerifier.cpp:4827: void (anonymous namespace)::SILVerifier::visitSILFunction(swift::SILFunction *): Assertion `F->isAvailableExternally() && "external declaration of internal SILFunction not allowed"' failed.
``` 
... followed by a stack dump...
on ubuntu, 
and similarly 
```
Assertion failed: (F->isAvailableExternally() && "external declaration of internal SILFunction not allowed"), function visitSILFunction, file /Users/buildnode/jenkins/workspace/oss-swift-5.0-package-osx/swift/lib/SIL/SILVerifier.cpp, line 4827. 
``` 
... followed by a stack dump...
on osx.

Running the tests on the version of Swift 5 prepackaged in the Travis CI job (osx_image: xcode10.2), everything builds, runs and passes fine. But I'm trying to get things working on linux again! Any idea what could be the issue here?

**Comment by kylef** [comment]
I don't think this has anything to do with swiftenv, you should raise this issue up with Swift itself.

https://swift.org/contributing/#reporting-bugs

**Comment by bwetherfield** [comment]
Ah okay, thanks

**Comment by kylef** [comment]
The Linux builds of Swift can be a bit different to the Swift included in Xcode even in the same version.

I've hit https://bugs.swift.org/browse/SR-10206 a couple of times already. Some of these compiler crashes can be worked around if you can figure which source line in your project is causing the Swift compiler to crash, for example https://github.com/kylef/PathKit/pull/69. You may be able to get some hint based on messages prior such as which file is being parsed.

**Comment by bwetherfield** [comment]
I got some new leads from this, thank you! Looking more closely over the
stack dumps :)

I guess I was surprised that I would get errors from a fresh install of
Swift 5 on osx compared with the Xcode version, but perhaps that tells us
there is a difference between those too!

**Comment by bwetherfield** [comment]
Seemingly found what was causing the issue if others are interested or encounter similar: https://bugs.swift.org/browse/SR-11048 . Thanks for the direction, @kylef !
