### ISSUE TITLE
getting path to libsourcekitdInProc.so

### ISSUE THREAD

**Issue by kelvin13** [kylef/swiftenv#159]
I’m trying to get my [atomic-blonde](https://atom.io/packages/atomic-blonde) plugin to use swiftenv to locate `libsourcekitdInProc.so`. does swiftenv provide a way to do this?

**Comment by kylef** [comment]
You can use `swiftenv prefix` to get the path to the Swift installation, not entirely sure that the Swift team include this dylib in the binary installs though.

```shell
$ swiftenv prefix
/Users/kyle/Library/Developer/Toolchains/swift-5.0-RELEASE.xctoolchain

$ ls (swiftenv prefix)/usr/lib
libIndexStore.dylib
libswiftDemangle.dylib
sourcekitd.framework
swift
swift_static
```
