### ISSUE TITLE
Support for Swift 5.1

### ISSUE THREAD

**Issue by paulofaria** [kylef/swiftenv#161]
How could I contribute to add support for Swift 5.1?

**Comment by kylef** [comment]
has Swift 5.1 came out? I don't see any 5.1 listed in Swift releases for download at https://swift.org/download/#releases

**Comment by paulofaria** [comment]
Sorry, I meant the development snapshot. Is it possible to specify it already?

**Comment by kylef** [comment]
Yes, it should be possible. As these snapshots move relatively fast and frequent, swiftenv will hit swiftenv-api to get a list (which crawls the list of versions every hour from swift download page -- https://github.com/kylef/swiftenv-api).

You can use the following to get a list:

```
$ swiftenv install --list-snapshots
```

There are some recent ones:

```
$ swiftenv install --list-snapshots | grep 2019-08
DEVELOPMENT-SNAPSHOT-2019-08-01-a
DEVELOPMENT-SNAPSHOT-2019-08-02-a
DEVELOPMENT-SNAPSHOT-2019-08-03-a
```

Along with some 5.1 specific snapshots (I don't recall what the difference is between these branches):

```shell
$ swiftenv install --list-snapshots | grep '^5.1'
5.1-DEVELOPMENT-SNAPSHOT-2019-04-16-a
5.1-DEVELOPMENT-SNAPSHOT-2019-04-17-a
...
5.1-DEVELOPMENT-SNAPSHOT-2019-07-23-a
5.1-DEVELOPMENT-SNAPSHOT-2019-07-24-a
5.1-DEVELOPMENT-SNAPSHOT-2019-07-25-a
```

You can pass these identifiers directly to `swiftenv install 5.1-DEVELOPMENT-SNAPSHOT-2019-07-25-a`, you may be able pass a URL to a particular snapshot tarball/pkg (platform dependent) although I am not sure how relaible that works, you can easily copy binary URL for wrong platform and it may not work.

**Comment by paulofaria** [comment]
Great! Thank you very much Kyle.
