### ISSUE TITLE
swiftenv.fuller.li is down

### ISSUE THREAD

**Issue by Samasaur1** [kylef/swiftenv#162]
Running `eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"` has been working for my projects, but today, it instead returned a Cloudflare error site. I was unable to capture the site before it appeared to return to serving the correct website, so I restarted my failed builds. However, they now say `curl: (51) SSL: no alternative certificate subject name matches target host name 'swiftenv.fuller.li'` and visiting the site in Safari says that `Safari can't establish a secure connection to the server "swiftenv.fuller.li"`. Using `curl` from my computer allows me to read the site, but I don't want to do so insecurely from Travis.

Is there anything I can do besides waiting for the site to be fixed?

**Comment by JosephDuffy** [comment]
I think in the interim you can use `eval "$(curl -sL https://raw.githubusercontent.com/kylef/swiftenv/master/docs/install.sh)"`, but I have also run in to this problem and would not like to point at the GitHub-hosted file in the long run, unless it become recommended.

**Comment by Samasaur1** [comment]
I'm using `eval "$(curl -sL https://swiftenv.fuller.li/install.sh || curl -sL https://raw.githubusercontent.com/kylef/swiftenv/master/docs/install.sh)"`, which tries the main website but uses the GitHub hosted one if the main site is unavailable. It seems to be working

**Comment by kylef** [comment]
Unfortunately, ReadTheDocs (the service I use to host the documentation) has had some implementation detail changes which have broken compatibility with the CDN used (CloudFlare).

As per the following in their documentation:

> Due to a limitation, a domain cannot be proxied on Cloudflare to another Cloudflare account that also proxies. This results in a “CNAME Cross-User Banned” error. In order to do SSL termination, we must proxy this connection.

This has caused a couple of problems, namely also breaking HTTPS for the service. I've managed to restore this by tweaking configuration.
