### ISSUE TITLE
Missing some dependencies when running on minimal installed Ubuntu

### ISSUE THREAD

**Issue by Cyberbeni** [kylef/swiftenv#165]
So I installed VirtualBox and Ubuntu 18.04.3 LTS on it with the minimal settings.
Installed git and curl with apt-get then I ran the `eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"` command which then I had compilation errors about missing libatomic1 and then some headers were not found, so I also had to apt-get clang

This was with swift 5.1.2

**Comment by kylef** [comment]
Yes, you will need to install any dependencies for Swift itself. At the moment that is clang and libicu-dev for Ubuntu, but consult Apple’s documentation for up-to date dependencies for newer Swift releases (https://swift.org/download/#linux):

> Install required dependencies:
> $ sudo apt-get install clang libicu-dev

More information can be found in [Swiftenv’s documentation](https://swiftenv.fuller.li/en/latest/commands.html#install)

> It is expected that all dependencies are already installed for running Swift, please consult the [Swift website](https://swift.org/download/#linux) for more information.
