### ISSUE TITLE
Support `latest` version

### ISSUE THREAD

**Issue by Cyberbeni** [kylef/swiftenv#166]
I'm making a [github action](https://github.com/Cyberbeni/install-swift-tool) to install swift tools, like Swiftformat or xcbeautify to use in workflows.
I would like to have an option to automatically download the latest version of swift if it's not available to use for building these tools.

This is just one use case but I think other people could also find this beneficial.

**Comment by kylef** [comment]
I have no intention to support this in swiftenv at this point in time. Swift continues to bring breaking changes in **patch** versions of Swift. I may revisit this if and when Swift ever reaches a point where there is long term source stability across multiple releases.

I would certainly not recommend doing it in CI, this will make the builds unreproducible over time. Historic builds can not be re-tried as the version of Swift may bring breaking changes for builds that previously worked. In the future, your working CI may being to fail when Swift makes a minor change.

**Comment by Cyberbeni** [comment]
GitHub also has the latest version of swift installed now, so it's not needed.
