### ISSUE TITLE
GitHub Actions Cache

### ISSUE THREAD

**Issue by xavierLowmiller** [kylef/swiftenv#167]
I'm trying to cache `swiftenv`'s downloads in my project's [GitHub Actions][].

I'm using [this action][yockow], which wraps `swiftenv`, to set up Swift on both macOS and Linux (see [my issue there][]).

Currently, I'm caching the action's workspace (`/home/runner/action-setup-swift-workspace`), which should contain all the `swiftenv` downloads (it's around 320 MB).
This, however, doesn't work and `swiftenv` starts the download again the next time the action is run.

<details>
  <summary>(This is my YAML block)</summary>
    - name: Cache Swift Version
       uses: actions/cache@master
       with:
         path: /home/runner/action-setup-swift-workspace
         key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
         restore-keys: |
           ${{ runner.os }}-spm-
</details>

Can you give me a hint which files/folders should be cached, so `swiftenv` doesn't start from scratch?

[GitHub Actions]: https://github.com/xavierLowmiller/app-parser/pull/3
[my issue there]: https://github.com/YOCKOW/Action-setup-swift/issues/31
[yockow]: https://github.com/YOCKOW/Action-setup-swift

**Comment by kylef** [comment]
By default the Swift versions should reside in `~/.swiftenv/versions` on Linux. This can be modified by setting the environment var `SWIFTENV_ROOT`.

```
$ tree ~/.swiftenv
├── shims
├── version          <- stores the global swift version to use (see https://swiftenv.fuller.li/en/latest/getting-started.html#switching-swift-versions)
└── versions         <- stores the versions on non macOS platforms
```

`~/.swiftenv/shims` should get created when you run `swiftenv init -` or manually via `swiftenv rehash`.

**Comment by xavierLowmiller** [comment]
Thanks for your answer!

Unfortunately, this doesn't solve my issue, but I don't think the problem is with `swiftenv`, so I'm closing this.

**Comment by kylef** [comment]
FWIW, I'd love to make an official swiftenv GitHub action and guide on how to use it. Unfortunately I haven't found the time to do it. Although if anyone is interested in contributing it that would be very welcome.

I'd imagine the use to be something like:

```yaml
steps:
  - uses: kylef/setup-swift
	with:
      swift-version: '5.0'
```

Then optionally some additional step to be able to cache swift version, although perhaps cache isn't that nessecery, not sure that downloading the tarball from swift.org vs downloading it from GitHub cache will be that much faster. Atleast that can be further steps if it is deemed to save much time (trade off between complexity vs time).

First step can just be figuring out how to manually setup swiftenv on GitHub actions ofc.

**Comment by xavierLowmiller** [comment]
> downloading the tarball from swift.org vs downloading it from GitHub cache will be that much faster

On my [measurement][], downloading the cache from the GitHub cache took 20 seconds, while the Swift setup took 50 seconds. It's not the world, but still...

I suppose that GitHub cache uses some sort of internal network infrastructure and doesn't hit the 'real' internet 🤷‍♂ 

Anyway, as I said, the time difference doesn't matter too much.

[measurement]: https://github.com/xavierLowmiller/app-parser/pull/3/checks?check_run_id=536419492

**Comment by xavierLowmiller** [comment]
I'd love to look into writing a GitHub action, too, but I'm currently quite busy as well.

I'll let you know if I find some time 👍
