### ISSUE TITLE
swiftenv says v 5.2 but xcode disagrees

### ISSUE THREAD

**Issue by philosopherdog** [kylef/swiftenv#171]
When I show the Swift Language Version in Xcode's Build Settings it reports the version as 5. swiftenv reports it at 5.2. What am I missing?

**Comment by kylef** [comment]
Please include the output of the following commands:

```
$ swiftenv versions --verbose
$ swift --version
```

**Comment by philosopherdog** [comment]
5.2 [from toolchain] (set by /Users/asceticcode/Workspace/sociables/sociables/sociables/.swift-version)
  5.2.2 [from xcode /Applications/Xcode.app]

Apple Swift version 5.2.2 (swiftlang-1103.0.32.6 clang-1103.0.32.51)
Target: x86_64-apple-darwin19.4.0

![Screenshot of Xcode (2020-05-02, 4-31-04 PM)](https://user-images.githubusercontent.com/530718/80891489-5d7fec80-8c92-11ea-9ddc-de6380389253.jpg)

**Comment by kylef** [comment]
Appears that Xcode is only showing the major version here where the swift bundled with it reports it is `5.2.2`. I don't think this is a question about swiftenv. Please consult the maintainers of Xcode why they are showing "Swift 5".

**Comment by ikesyo** [comment]
Those shown in Xcode are language modes, not actual language versions.

- Swift 4.0: Swift 4 mode
- Swift 4.1: Swift 4 mode
- Swift 4.2: Swift 4.2 mode
- Swift 5.0: Swift 5 mode
- Swift 5.1: Swift 5 mode
- Swift 5.2: Swift 5 mode

**Comment by philosopherdog** [comment]
Awesome thanx guys.
