### ISSUE TITLE
Doesn't switch swift with ZSH

### ISSUE THREAD

**Issue by MihaelIsaev** [kylef/swiftenv#173]
Trying to switch swift by `swiftenv global 5.2.2` and it works perfectly with bash, but with zsh it always shows system version of swift.

So with bash I see that swift is at `/Users/mik/.swiftenv/shims/swift`
With zsh it is at `/user/bin/swift`

**Comment by kylef** [comment]
@MihaelIsaev have you followed [step 2 for ZSH in the installation guide](https://swiftenv.fuller.li/en/latest/installation.html)? Given those symptons it would suggest the invocation to load the shims into the $PATH is missing.

**Comment by MihaelIsaev** [comment]
yeah and I checked my `~/.zshenv` it contains
```
export SWIFTENV_ROOT="$HOME/.swiftenv"
export PATH="$SWIFTENV_ROOT/bin:$PATH"
eval "$(swiftenv init -)"
```
maybe I missed something else?
I switched to zsh just a few days ago by executing `chsh -s /bin/zsh`

**Comment by kylef** [comment]
Once your inside zsh, if you run `source ~/.zshenv` does that enable swiftenv to work? Or alternatively pasting those commands into terminal.

I wonder if `zshenv` may be a bit too early in the zsh lifecycle, I haven’t tried putting swiftenv setup in there, only in `~/.zshrc`.

**Comment by MihaelIsaev** [comment]
if I execute `eval "$(swiftenv init -)"` once then it works so it looks like that command won't execute from `~/.zshrc` while `export` works well there

<img width="650" alt="Screenshot 2020-05-23 at 22 23 32" src="https://user-images.githubusercontent.com/1272610/82737709-0aa2cd80-9d44-11ea-9753-6c7f3656e815.png">
<img width="752" alt="Screenshot 2020-05-23 at 22 23 42" src="https://user-images.githubusercontent.com/1272610/82737714-1098ae80-9d44-11ea-9b63-3764141a5267.png">

**Comment by MihaelIsaev** [comment]
Fixed it by moving everything from `.zshenv` into `.zlogin`
