### ISSUE TITLE
add support for Swift 5.3

### ISSUE THREAD

**Issue by dastrobu** [kylef/swiftenv#179]
according to https://swift.org/blog/ Swift 5.3 is released. When configuring 5.3 in my swift builds on travis CI i get:
```
 eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
Cloning into '/home/travis/.swiftenv'...
remote: Enumerating objects: 107, done.
remote: Counting objects: 100% (107/107), done.
remote: Compressing objects: 100% (81/81), done.
remote: Total 107 (delta 22), reused 61 (delta 17), pack-reused 0
Receiving objects: 100% (107/107), 106.03 KiB | 3.66 MiB/s, done.
Resolving deltas: 100% (22/22), done.
We don't have build instructions for 5.3.
```

That seems to indicate that something needs to be done to install Swift 5.3 via swiftenv. 

If there is anything I can do to help getting Swift 5.3 to work, I will be happy to help.

**Comment by oxcug** [comment]
Just hit this. Also happy to help where I can.

**Comment by kylef** [comment]
I've added Swift 5.3 to the binary sources now.

@dastrobu If you re-trigger the build it should be working now (I've forked and done this here: https://travis-ci.org/github/kylef-archive/vincenty/builds/728608558). Let me know if you're having any other problems.

@oxcug Are you seeing this still if you re-trigger still? If so please share a link to the repo/branch and I'll take a look.

**Comment by dastrobu** [comment]
Thanks for the quick fix. Build works now.
