### ISSUE TITLE
Unable to uninstall existing version

### ISSUE THREAD

**Issue by deepumukundan** [kylef/swiftenv#18]
Hi Kyle,

Good to see swiftenv getting updated to 1.0

I was trying to uninstall a version of swift I have installed using swiftenv.
But swiftenv stated that the version is not installed. Attaching a screenshot.

<img width="419" alt="screen shot 2016-03-21 at 6 19 17 pm" src="https://cloud.githubusercontent.com/assets/1459484/13939331/7bf094f0-ef91-11e5-8cf0-e70fba039b8f.png">

**Comment by kylef** [comment]
Hi @deepumukundan,

On OS X we're installing a Swift toolchain which isn't handled in uninstallation yet. I'll take a look to adding support this evening.

**Comment by MatthiasWinkelmann** [comment]
This may warrant a quick note in the doc or on the command line... I just spent entirely too much time reading source code before I found this issue.

**Comment by kylef** [comment]
@MatthiasWinkelmann Sorry, it will be handled in the next release (and current master). I'll make a new release shortly, I just want to make some other minor changes beforehand.
