### ISSUE TITLE
swiftenv install --list-snapshots returns 502 Bad Gateway

### ISSUE THREAD

**Issue by robertlyson** [kylef/swiftenv#194]
When running the command `swiftenv install --list-snapshots`, I am receiving a 502 Bad Gateway error.

<img width="515" alt="image" src="https://github.com/kylef/swiftenv/assets/2392583/260d2c50-9019-4470-8c93-0b53b47f0ea9">

After investigating code base looks like https://swiftenv-api.fuller.li/ is not working
<img width="924" alt="image" src="https://github.com/kylef/swiftenv/assets/2392583/fc0e3865-d10b-4a43-8252-15308211686b">

Could someone please give it a restart? Thanks :)

**Comment by kylef** [comment]
Seems it was down on all backends for a while. Service was not configured to launch of system boot. This is sorted now.
