### ISSUE TITLE
Pointer to most recent version

### ISSUE THREAD

**Issue by adrianbrink** [kylef/swiftenv#20]
Hi,

I can use swiftenv install dev-3.0 to install that version. However how can I find the most up-to-date version of the master branch on the swift website?

Maybe swiftenv install newest would be a nice command :-)

**Comment by kylef** [comment]
You can use `swiftenv install 3.0-dev` and `swiftenv install 2.2-dev` to build and install the very latest from the respective branches directly from git.

Checkout our documentation on [Building Swift from Source](https://swiftenv.fuller.li/en/latest/building-swift.html).

**Comment by adrianbrink** [comment]
Thank you :-)
