### ISSUE TITLE
Unable to switch to 2.2

### ISSUE THREAD

**Issue by adrianbrink** [kylef/swiftenv#21]
Hi,

I am using swiftenv local 2.2 or swiftenv global 2.2, however when running swift --version it still shows swift 3.0?

Any idea why that is happening? :-)

Thank you very much.

**Comment by kylef** [comment]
@adrianbrink Can you run the following and share the output:

```shell
$ swiftenv versions
$ echo $PATH
```

**Comment by adrianbrink** [comment]
I fixed it. Deleting swiftenv, reinstalling and then it all worked. For some reason though I can't install swift from source. It fails with on an invocation of Xcode. I'm guessing that this isn't the right space for that, but if you are knowledgable and willing to help I could post the log file. :-)

Thank you very much :-)

**Comment by kylef** [comment]
Can you paste the log to some paste site and then attach a link here and I can take a look. Also, how much memory do you have? Swift is known of fail unless it has a lot of ram.

**Comment by iamcam** [comment]
I'm having the same issue:
`swiftenv version` shows the selected package (and I believe it is actually building with this one)

```
$ cameron:~ 🌎  swiftenv version
DEVELOPMENT-SNAPSHOT-2016-02-08-a (set by /Users/cameron/.swiftenv/version)
```

However, running `swift --version` gives me something entirely different

```
$ cameron:~ 🌎  swift --version
Apple Swift version 3.0-dev (LLVM a7663bb722, Clang 4ca3c7fa28, Swift 1c2f40e246)
Target: x86_64-apple-macosx10.9
```

I'm sure at some point I actually build Swift3.0, but I honestly don't recall when. I certainly haven't been using it. All this is stranger when I see which swift is actually being run:

```
$ cameron 🌎  which swift
/Users/cameron/.swiftenv/shims/swift
```
The  relevant parts of my `.bash_profile` are
```
export PATH=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin:"${PATH}"
export SWIFTENV_ROOT="$HOME/.swiftenv"
export PATH="$SWIFTENV_ROOT/bin:$PATH"
eval "$(swiftenv init -)"
if which swiftenv > /dev/null; then eval "$(swiftenv init -)"; fi
```

**Comment by kylef** [comment]
@iamcam I don't see any problems in what you've shown.

The DEVELOPMENT-SNAPSHOT-2016-02-08-a snapshot will show `3.0-dev (LLVM a7663bb722, Clang 4ca3c7fa28, Swift 1c2f40e246)` from `swift --version`. These commit hashes are the hashes that are tagged with `DEVELOPMENT-SNAPSHOT-2016-02-08-a`. If you take a look at the last commit on https://github.com/apple/swift/tree/swift-DEVELOPMENT-SNAPSHOT-2016-02-08-a it is `1c2f40e2464eca0c110cbde286d83b9e79fe5e90 ` as shown in `swift --version`.

```shell
$ env SWIFT_VERSION="DEVELOPMENT-SNAPSHOT-2016-02-08-a" swift --version
Apple Swift version 3.0-dev (LLVM a7663bb722, Clang 4ca3c7fa28, Swift 1c2f40e246)
Target: x86_64-apple-macosx10.9

$ env SWIFT_VERSION="DEVELOPMENT-SNAPSHOT-2016-03-01-a" swift --version
Apple Swift version 3.0-dev (LLVM b361b0fc05, Clang 11493b0f62, Swift 24a0c3de75)
Target: x86_64-apple-macosx10.9
```

**Comment by kylef** [comment]
@adrianbrink I'm not able to reproduce your build error, I think it was either resolved upstream by the Swift team or via https://github.com/kylef/swiftenv/commit/f26a42b1b03a41d3433fe599643349cca87f9edc

Please let me know if your still having problems.
