### ISSUE TITLE
swift --version is still 2.2

### ISSUE THREAD

**Issue by zdenektopic** [kylef/swiftenv#22]
I am trying to install DEVELOPMENT-SNAPSHOT-2016-02-08-a.

install works ok
then i do `swiftenv local DEVELOPMENT-SNAPSHOT-2016-02-08-a` in directory, but `swift --version` outputs

> Apple Swift version 2.2 (swiftlang-703.0.18.1 clang-703.0.29)
> Target: x86_64-apple-macosx10.9

I have installed swiftenv via brew with --HEAD

El Capitan 10.11.4

**Comment by kylef** [comment]
Can you run the following and share the output here.

```shell
$ echo $PATH
$ which swift
```

-Kyle

**Comment by zdenektopic** [comment]
> Zdenek-MBP:zewo-test zdenektopic$ echo $PATH
> /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
> Zdenek-MBP:zewo-test zdenektopic$ which swift
> /usr/bin/swift

**Comment by kylef** [comment]
@zdenektopic Please see the additional installation instructions for Homebrew: https://swiftenv.fuller.li/en/latest/installation.html#via-homebrew You will need to follow step 2.

**Comment by gavrix** [comment]
Can you please suggest what PATH _should_ look like install?

**Comment by kylef** [comment]
@gavrix Once you've added the line to your shell's profile. The location of the shims will be injected into the PATH, something like `$HOME/.swiftenv/shims`.

**Comment by gavrix** [comment]
@kylef thank you, it helped!
