### ISSUE TITLE
unable to switch to 2.2.x branch

### ISSUE THREAD

**Issue by cometyang** [kylef/swiftenv#23]

**Comment by cometyang** [comment]
have to use full path instead of only "swiftenv install swift-2.2.1-SNAPSHOT-2016-03-28-a"

**Comment by crewshin** [comment]
Same issue here. Problem is the first part of the path it's searching for:

https://swift.org/builds/swift-2.2.1-branch <- doesn't exist (yet).

This is the actual url: `https://swift.org/builds/swift-2.2-branch/xcode/swift-2.2.1-SNAPSHOT-2016-04-12-a/swift-2.2.1-SNAPSHOT-2016-04-12-a-osx.pkg`
