### ISSUE TITLE
Request: support for aliases

### ISSUE THREAD

**Issue by ianpartridge** [kylef/swiftenv#25]
The development snapshot names are long and tedious to type/copy.

```
ipartrid@apus:~$ swiftenv versions
  DEVELOPMENT-SNAPSHOT-2016-03-24-a
  DEVELOPMENT-SNAPSHOT-2016-04-12-a
  DEVELOPMENT-SNAPSHOT-2016-04-25-a
* 2.2 (set by /Users/ipartrid/.swiftenv/version)
ipartrid@apus:~$ swiftenv local DEVELOPMENT-SNAPSHOT-2016-04-25-a
ipartrid@apus:~$
```

It would be nice to be able to do:

```
ipartrid@apus:~$ swiftenv alias dev=DEVELOPMENT-SNAPSHOT-2016-04-25-a
ipartrid@apus:~$ swiftenv local dev
```

**Comment by kylef** [comment]
Hi @ianpartridge,

While, this doesn't have a nice fronted to add aliases. They are actually supported internally, if you manually make a symbolic link for the version.

For example:

```shell
# Find the location for the version
$ swiftenv prefix DEVELOPMENT-SNAPSHOT-2016-03-01-a
/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-03-01-a.xctoolchain

# Create a symbolic link to the version into `~/.swiftenv/versions/dev`
$ ln -s /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-03-01-a.xctoolchain ~/.swiftenv/versions/dev

# Set local swift to new aliased version
$ swiftenv local dev
```

**Comment by kylef** [comment]
I'd like to add support so that if you do `swiftenv local` it would save the original swift version (`DEVELOPMENT-SNAPSHOT-2016-03-01-a` in this case to the `.swift-version` file instead of `dev`) in the future. But what I've shown above should solve your use-case for now.

**Comment by ianpartridge** [comment]
Thanks Kyle, it does.  And thanks for writing `swiftenv`, it's awesome!
