### ISSUE TITLE
Issues when installing on Ubuntu 16.04

### ISSUE THREAD

**Issue by dlaynes** [kylef/swiftenv#26]
Hi, I'm trying to install both 2.2 and 3.0-dev versions, and I'm getting the following error message in the logs:
Can't find source directory for ninja (tried ~/.swiftenv/tmp/swiftenv-build-3.0-dev/ninja)

Do I need to clone github.com/martine/ninja in that directory? If so, which version do I need?
Thanks.

**Comment by kylef** [comment]
@dlaynes Hi, when building swift from source, you will need to install all of the development dependencies for Swift itself.

This list of dependencies can be found in our documentation at https://swiftenv.fuller.li/en/latest/building-swift.html#ubuntu

So, for Ubuntu this should be all of the following, including ninja-build.

```shell
$ sudo apt-get install git cmake ninja-build clang python uuid-dev libicu-dev icu-devtools libbsd-dev libedit-dev libxml2-dev libsqlite3-dev swig libpython-dev libncurses5-dev pkg-config
```

**Comment by dlaynes** [comment]
Sorry for not updating my status on this issue.
I'm getting these error messages on the log. I'll try to figure out what is wrong with my environment, and may open a new issue. Regards.

/home/donato/.swiftenv/tmp/swiftenv-build-3.0-dev/swift/lib/ClangImporter/ClangImporter.cpp:3686:59: error: too few arguments to function call, expected at least 4, have 3
                                          isInstanceMethod);
                                                          ^
/home/donato/.swiftenv/tmp/swiftenv-build-3.0-dev/llvm/tools/clang/include/clang/Sema/Sema.h:3169:3: note: 'CollectMultipleMethodsInGlobalPool' declared here
  bool
  ^
/home/donato/.swiftenv/tmp/swiftenv-build-3.0-dev/swift/lib/ClangImporter/ClangImporter.cpp:3764:65: error: too few arguments to function call, expected at least 4, have 3
                                               /*instance=*/true);

**Comment by montj2** [comment]
@dlaynes Were you able to resolve 
`~/.swiftenv/tmp/swiftenv-build-3.0-dev/swift/lib/ClangImporter/ClangImporter.cpp:3686:59: error: too few arguments to function call, expected at least 4, have 3
isInstanceMethod);`
As I am encountering the same issue and cannot seem to locate a similar issue on the 3.0 branch.

**Comment by dlaynes** [comment]
There are no development builds of Swift 2 or 3 for Ubuntu 16.04, in the official website.
I asume the latest Ubuntu won't have support for a while.

Regards.



---- On Thu, 12 May 2016 16:35:30 -0500 James &lt;notifications@github.com&gt;wrote ---- 




@dlaynes Were you able to resolve 

 ~/.swiftenv/tmp/swiftenv-build-3.0-dev/swift/lib/ClangImporter/ClangImporter.cpp:3686:59: error: too few arguments to function call, expected at least 4, have 3
 isInstanceMethod);
As I am encountering the same issue and cannot seem to locate a similar issue on the 3.0 branch.

**Comment by montj2** [comment]
@dlaynes Thank you. I am getting the same error on 14.04, also. There may be more to this or something I've overlooked.

**Comment by m-barthelemy** [comment]
Same error here, trying to compile swift-DEVELOPMENT-SNAPSHOT-2016-05-09-a

**Comment by kylef** [comment]
> Same error here, trying to compile swift-DEVELOPMENT-SNAPSHOT-2016-05-09-a on Ubuntu 14.04

@m-barthelemy swiftenv doesn't allow you to compile snapshots. Do you mean downloading the binary release? Please file a separate issue with the error you are facing.

**Comment by kylef** [comment]
As for the actual build errors, these should have been resolved by https://github.com/kylef/swiftenv/commit/f26a42b1b03a41d3433fe599643349cca87f9edc .

**Comment by dlaynes** [comment]
Thanks for your update and efforts.
In some environments (like my own laptop) people might run into this bug
https://bugs.swift.org/browse/SR-1023

`
++ product=swift
++ [[ Ninja == \X\c\o\d\e ]]
+ /usr/bin/cmake --build ~/.swiftenv/tmp/swiftenv-build-3.0-dev/build/Ninja-ReleaseAssert/swift-linux-x86_64 -- -j4 -j4 all swift-test-stdlib-linux-x86_64
[1/31] Symlinking Clang resource headers into ~/.swiftenv/tmp/swiftenv-build-3.0-dev/build/Ninja-ReleaseAssert/swift-linux-x86_64/./lib/swift/clang
[2/31] Linking CXX shared library lib/swift/linux/x86_64/libswiftCore.so
FAILED: : && /usr/bin/clang++  -fPIC -fno-stack-protector -fPIC -fvisibility-inlines-hidden -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wcovered-switch-default -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Werror=date-time -std=c++11 -fcolor-diagnostics -ffunction-sections -fdata-sections -Wdocumentation -Wimplicit-fallthrough -Wunreachable-code -Woverloaded-virtual -O3  -Wl,-z,defs   -target x86_64-unknown-linux-gnu -isysroot / -lpthread -ldl  -L~/.swiftenv/tmp/swiftenv-build-3.0-dev/build/Ninja-ReleaseAssert/swift-linux-x86_64/./lib/swift/linux/x86_64 -L~/.swiftenv/tmp/swiftenv-build-3.0-dev/build/Ninja-ReleaseAssert/swift-linux-x86_64/./bin/../lib/swift/linux/x86_64 -L~/.swiftenv/tmp/swiftenv-build-3.0-dev/build/Ninja-ReleaseAssert/swift-linux-x86_64/./bin/../lib/swift/linux -shared -Wl,-soname,libswiftCore.so -o lib/swift/linux/x86_64/libswiftCore.so lib/swift/linux/x86_64/swift_begin.o stdlib/public/core/linux/x86_64/Swift.o lib/swift/linux/x86_64/swift_end.o -L~/.swiftenv/tmp/swiftenv-build-3.0-dev/build/Ninja-ReleaseAssert/llvm-linux-x86_64/lib  -L~/.swiftenv/tmp/swiftenv-build-3.0-dev/build/Ninja-ReleaseAssert/llvm-linux-x86_64/./lib lib/swift/linux/x86_64/libswiftRuntime.a lib/swift/linux/x86_64/libswiftStdlibStubs.a -licuuc -licui18n -Wl,-rpath,"\$ORIGIN:/usr/lib/swift/linux" && :
/usr/bin/ld: stdlib/public/core/linux/x86_64/Swift.o: relocation R_X86_64_PC32 against protected symbol `_TMPSa' can not be used when making a shared object
/usr/bin/ld: final link failed: Bad value
`
