### ISSUE TITLE
curl timeout

### ISSUE THREAD

**Issue by mikaelbartlett** [kylef/swiftenv#28]
curl: (28) Operation timed out after 89999 milliseconds with 113328128 out of 211085000 bytes received

Is it possible to increase the timeout?

**Comment by kylef** [comment]
The timeout is 90 seconds, I think that's a pretty large timeout already.

Which command did you run that resulted in this error?

**Comment by mikaelbartlett** [comment]
swiftenv install DEVELOPMENT-SNAPSHOT-2016-04-12-a

I see progress downloading but stops because of the timeout.

**Comment by mikaelbartlett** [comment]
############                                                              17.1%* Operation timed out after 89999 milliseconds with 35999744 out of 211085000 bytes received

The download was progressing but ended because of the timeout

**Comment by mikaelbartlett** [comment]
Any suggestions?

**Comment by kylef** [comment]
I'm not too sure what's happening here.

Would you be able to try invoking curl manually with the verbose options to see what it says.

```shell
$ curl -O -v https://swift.org/builds/development/xcode/swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a/swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a-osx.pkg swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a-osx.pkg
```

**Comment by mikaelbartlett** [comment]
Gives the same timeout. Did some further investigation and it does explicitly says that max-time has no default value but setting max-time to a high value makes the download complete.

`curl -O -v https://swift.org/builds/development/xcode/swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a/swift-DEVELOPMENT-SNAPSHOT-2016-04-12-a-osx.pkg -m 6000`

I've tried adding -m 6000 in swiftenv and it completed the installation.

So rather this is a cURL issue.

**Comment by kylef** [comment]
What's weird, is that for me it doesn't timeout at 90 seconds. My download took 140 seconds to complete and completed successfully.

```
$ swiftenv install DEVELOPMENT-SNAPSHOT-2016-05-09-a
Downloading https://swift.org/builds/development/xcode/swift-DEVELOPMENT-SNAPSHOT-2016-05-09-a/swift-DEVELOPMENT-SNAPSHOT-2016-05-09-a-osx.pkg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  228M  100  228M    0     0  1664k      0  0:02:20  0:02:20 --:--:-- 1673k
```

Are you running the version of curl installed my OS X or have you manually installed a different version?

What is the output for version?

```shell
$ curl --version
curl 7.43.0 (x86_64-apple-darwin15.0) libcurl/7.43.0 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets
```

**Comment by mikaelbartlett** [comment]
```
curl 7.43.0 (x86_64-apple-darwin15.0) libcurl/7.43.0 SecureTransport zlib/1.2.5
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tufts
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets
```
