### ISSUE TITLE
Homebrew package issue

### ISSUE THREAD

**Issue by ChrisChinchilla** [kylef/swiftenv#29]
I'm not completely sure where the problem lies, but I'm going to report it anyway and you can decide…

After an hombrew upgrade to swiftenv I found that all the shims were incorrect, i.e. _shims/swiftc_

```
#!/usr/bin/env bash
set -e
exec "/usr/local/Cellar/swiftenv/1.0.0/bin/../libexec/swiftenv" exec "--shim" "swiftc" "$@"
```

instead of 

```
#!/usr/bin/env bash
set -e
exec "/usr/local/Cellar/swiftenv/1.0.1/bin/../libexec/swiftenv" exec "--shim" "swiftc" "$@"
```

And I had to update all the references to 1.0.1 manually, then swift worked again.

I hope that issue report helps and let me know if you want any other details.

**Comment by kylef** [comment]
Thanks for reporting @ChrisChinchilla, this can be easily updated via `swiftenv rehash`. I've made changes in #30 to automatically run swiftenv rehash when you switch versions of swiftenv so this would be automatic.
