### ISSUE TITLE
Swift-3.0 Preview-Branch Snapshots have malformed download links

### ISSUE THREAD

**Issue by Danappelxx** [kylef/swiftenv#31]
To reproduce:

```sh
$> swiftenv install swift-3.0-preview-1-SNAPSHOT-2016-05-31-a
3.0-preview-1-SNAPSHOT-2016-05-31-a was not found on swift.org.
  https://swift.org/builds/swift-3.0-branch/xcode/swift-3.0-preview-1-SNAPSHOT-2016-05-31-a/swift-3.0-preview-1-SNAPSHOT-2016-05-31-a-osx.pkg
```

For previous snapshots, the base path was `swift.org/builds/swift-3.0/branch`. For these new preview snapshots, however, the base path changed to `swift.org/builds/swift-3.0-preview-<version>-branch`

For example: [`https://swift.org/builds/swift-3.0-preview-1-branch/xcode/swift-3.0-preview-1-SNAPSHOT-2016-05-31-a/swift-3.0-preview-1-SNAPSHOT-2016-05-31-a-osx.pkg`](https://swift.org/builds/swift-3.0-preview-1-branch/xcode/swift-3.0-preview-1-SNAPSHOT-2016-05-31-a/swift-3.0-preview-1-SNAPSHOT-2016-05-31-a-osx.pkg).

I will create new issues for other bugs I run into.

**Comment by kylef** [comment]
Which version of swiftenv are you using?

**Comment by Danappelxx** [comment]
0.5.0 (at least, that's what `swiftenv --version` prints out).

**Comment by kylef** [comment]
0.5.0 is quite an old release of swiftenv. Please update to swiftenv 1.0.2 which should work with preview-1. Let me know if you're still having problems afterwards.

**Comment by Danappelxx** [comment]
Ah, sorry about that - updating version right now. Hopefully that will fix the issue 👍
