### ISSUE TITLE
Can't find Swift version when manually install Swift for current user only

### ISSUE THREAD

**Issue by bingcheung** [kylef/swiftenv#35]
In OS X, when I use Swift Binary Package `.pkg` manually install for current user only, which install Swift into `~/Library/Developer/Toolchains/`, and then run `swiftenv rehash`,  it does't show current installed Swift version by running `switenv versions`  
But it works when *install for all users*  
***
OS X 10.11.4
swiftenv 1.0.2
Swift DEVELOPMENT-SNAPSHOT-2016-06-06-a

**Comment by kylef** [comment]
Hi @bingcheung,

Thanks for reporting, I wasn't aware that you could install toolchains directly into your own user only (perhaps this is new?). Anyways, I've added support for it into swiftenv and it's available in swiftenv 1.1.0. These versions should start appearing if you update to swiftenv 1.1.0.

Let me know if you have any problems.
