### ISSUE TITLE
install fails on FreeBSD

### ISSUE THREAD

**Issue by hamin** [kylef/swiftenv#36]
First off thank you for building swiftenv. I've been using it on my mac for a while now :).

I'm not too familiar with FreeBSD, but I installed the depenceids that you detailed in the wiki. After that I tried to build swift on FreeBSD and I run into this error:

```
[freebsd@free-haris ~]$ swiftenv install 3.0-dev
Found swift, skipping download
Found compiler-rt, skipping download
Found llvm, skipping download
Found clang, skipping download
Found lldb, skipping download
Found cmark, skipping download
Found swiftpm, skipping download
Found llbuild, skipping download
Found swift-corelibs-xctest, skipping download
Found swift-corelibs-foundation, skipping download
Found swift-corelibs-libdispatch, skipping download
Building Swift
This may take a very long time...
Building Swift failed
Check out the logfile for more information: /home/freebsd/.swiftenv/tmp/swiftenv-build-3.0-dev/swiftenv-build.20160608060410.1397.log
You can inspect or delete the working tree at: /home/freebsd/.swiftenv/tmp/swiftenv-build-3.0-dev
```

If I cat the log file this is what I get:

```
[freebsd@free-haris ~]$ cat /home/freebsd/.swiftenv/tmp/swiftenv-build-3.0-dev/swiftenv-build.20160608055536.1199.log
Cloning into 'swift'...
Checking out files: 100% (10799/10799), done.
Cloning into 'compiler-rt'...
Cloning into 'llvm'...
Checking out files: 100% (20127/20127), done.
Cloning into 'clang'...
Checking out files: 100% (11768/11768), done.
Cloning into 'lldb'...
Checking out files: 100% (5479/5479), done.
Cloning into 'cmark'...
Cloning into 'swiftpm'...
Cloning into 'llbuild'...
Cloning into 'swift-corelibs-xctest'...
Cloning into 'swift-corelibs-foundation'...
Cloning into 'swift-corelibs-libdispatch'...
usage: 
  build-script [-h | --help] [OPTION ...]
  build-script --preset=NAME [SUBSTITUTION ...]
build-script: error: unknown argument: --build-jobs
```
Any ideas?

**Comment by bingcheung** [comment]
Hi @hamin   
It seems Swift does not officially support FreeBSD, right?  
Maybe this is the key

**Comment by kylef** [comment]
Looks like the --build-jobs flag is no longer supported (https://github.com/apple/swift/pull/2834). I've made a change in swiftenv to no longer set this. Would you be able to pull these swiftenv changes and give it another try @hamin.

**Comment by hamin** [comment]
@kylef different error this time:

```
[freebsd@free-haris ~]$ cat  /home/freebsd/.swiftenv/tmp/swiftenv-build-3.0-dev/swiftenv-build.20160608203239.960.log
Cloning into 'swift'...
Checking out files: 100% (10800/10800), done.
Cloning into 'compiler-rt'...
Cloning into 'llvm'...
Checking out files: 100% (20127/20127), done.
Cloning into 'clang'...
Checking out files: 100% (11768/11768), done.
Cloning into 'lldb'...
Checking out files: 100% (5479/5479), done.
Cloning into 'cmark'...
Cloning into 'swiftpm'...
Cloning into 'llbuild'...
Cloning into 'swift-corelibs-xctest'...
Cloning into 'swift-corelibs-foundation'...
Cloning into 'swift-corelibs-libdispatch'...
Traceback (most recent call last):
  File "./utils/build-script", line 1536, in <module>
    sys.exit(main())
  File "./utils/build-script", line 1532, in main
    return main_normal()
  File "./utils/build-script", line 1034, in main_normal
    toolchain = host_toolchain(xcrun_toolchain=args.darwin_xcrun_toolchain)
  File "/usr/home/freebsd/.swiftenv/tmp/swiftenv-build-3.0-dev/swift/utils/swift_build_support/swift_build_support/toolchain.py", line 175, in host_toolchain
    return FreeBSD()
  File "/usr/home/freebsd/.swiftenv/tmp/swiftenv-build-3.0-dev/swift/utils/swift_build_support/swift_build_support/toolchain.py", line 143, in __init__
    if self._release_date and self._release_date >= 1100000:
  File "/usr/home/freebsd/.swiftenv/tmp/swiftenv-build-3.0-dev/swift/utils/swift_build_support/swift_build_support/cache_util.py", line 54, in __get__
    result = func(obj)
TypeError: _release_date() takes no arguments (1 given)
```

**Comment by hamin** [comment]
@kylef ^^ let me know what u think, looks like a small bug...but i can test fairly soon :)

**Comment by kylef** [comment]
I'm not too sure what's happening here, haven't had time to look at it yet. I think this is most likely a bug in Swift's build tools itself. swiftenv is just calling `./utils/build-script -R -- --install-prefix="$destination"` to build Swift and just a small wrapper around the underlying build scripts in Swift.

There has been a few changes to the build-script recently (https://github.com/apple/swift/pulls?utf8=✓&q=is%3Apr+is%3Aclosed+build-script) and it would appear that https://github.com/apple/swift/pull/2880 will refactor the logic around where the exception was raised.

**Comment by ddunbar** [comment]
FYI, `--build-jobs` is now `--jobs` or `-j` (a la Make, Ninja, etc.).

**Comment by hamin** [comment]
@ddunbar awesome!

**Comment by ddunbar** [comment]
The FreeBSD fix is merged, please let me know if you see additional issues (I don't actually have a FreeBSD environment to test with).

**Comment by hamin** [comment]
@ddunbar will do, I actually just started a FreeBSD digital ocean box to test how swift+libdispatch would work on FreeBSD. @kylef will `swiftenv install 3.0-dev` pick up the latest changes @ddunbar just did for the FreeBSD fix or do we have to wait for a new dev build ?

**Comment by kylef** [comment]
@hamin It won't if it previously failed. swiftenv will leave everything as-is when it failed so you can manually debug. You can delete the build directory and then reinstall.

```shell
$ rm ~/.swiftenv/tmp/swiftenv-build-3.0-dev
$ swiftenv install 3.0-dev --no-clean
```

**Comment by kylef** [comment]
Thanks for catching this and fixing upstream @ddunbar.
