### ISSUE TITLE
Platform-agnostic .swift-version file

### ISSUE THREAD

**Issue by Danappelxx** [kylef/swiftenv#37]
With the new Swift snapshot that we get from Xcode 8, it is now impossible (as far as I am aware, _please_ correct me if I'm wrong) to pin the proper Swift version on both OSX and Ubuntu. On OSX, the version is `3.0`. On Ubuntu, the correct version is `swift-3.0-preview-1`. 

What's the best approach/solution here?

**Comment by kylef** [comment]
I'd say this is a radar worthy problem. `swift` preview 3 shouldn't say it's version `3.0` which isn't out yet, but instead the preview.

```shell
$ swift --version
Apple Swift version 3.0 (swiftlang-800.0.30 clang-800.0.24)
```

There isn't really a way to differentiate this version between other 3.0 previews or even the final 3.0.

**Comment by ddunbar** [comment]
Historically we don't discriminate between those in our compiler version strings. If you feel it is important, I recommend raising a bug on bugs.swift.org for it and we can discuss it there.

**Comment by Danappelxx** [comment]
Ok, so in my opinion the best solution here (which is also additive) would be to have the ability to define platform-specific `.swift-version`'s.

Something like:

```
.swift-version: 3.0-preview-1
.swift-version.darwin: 3.0
```

Where `swiftenv` would first search `.swift-version`, and then override that selection with the platform-specific version file if it exists.

**Comment by Danappelxx** [comment]
In reply to your [last comment](https://github.com/kylef/swiftenv/pull/41#issuecomment-227900572)

Adding the alias actually seems like a good solution to me. Perhaps swiftenv could include that in the `rehash` step? That way we don't have to include that (somewhat messy) step in our CI or installation instructions. With the previews, using `swiftenv` should feel really smooth.

**Comment by paulofaria** [comment]
Hey @kylef I don't know if you know about SwiftPM slack

 [swiftpm.slack.io](swiftpm.slack.io)

@ddunbar and the crew is there. maybe we can discuss more the issue there with more people involved.

**Comment by ddunbar** [comment]
For now, the `swiftlang-800.0.30` tag uniquely identifiers the version of swiftc as "the version we shipped with Xcode 8 beta 1", which is derived from the swift-3-preview-1 branch. I realize this is gross, but it would work for swiftenv to "know" this -- there are only going to be a small finite number of such swiftlangs.

I would reiterate my previous comment that if the goal here is that swiftenv be able to "infer" the lineage of the swiftc from its version number and track back to a branch, we should get a JIRA for that on bugs.swift.org (and it seems like it might be a reasonable feature, I don't know that anyone would object, but lets discuss it there).
