### ISSUE TITLE
swift-build exists in shims when 2.2 is active.

### ISSUE THREAD

**Issue by helje5** [kylef/swiftenv#38]
When switching from a 3.0 version of Swift back to a 2.2 version, the shims still contain `swift-build`. This causes detection scripts to assume they can use SPM when they can't.

**Comment by kylef** [comment]
Hi @helje5,

When you're talking about detection scripts, are these some third parties ones or ones built into swift itself?

I'd expect any third-parties ones shouldn't rely on the internal implementation details of Swift CLI.

**Comment by helje5** [comment]
3rd party. A 3rd party needs to be able to choose whether it can use SPM or not. With your current setup a Swift 2 install looks like it can provide SPM when in fact it cannot. This has nothing to do with internal implementation details.

**Comment by kylef** [comment]
@helje5 I believe these are swift implementation details that the swift-build is a separate binary, and the `swift` binary itself doesn't handle these commands directly (but instead invokes a separate binary).

---

I'm not too sure how it would be possible for the shim `swift-build` to not exist for certain Swift versions. Do you have any ideas?

**Comment by helje5** [comment]
I'm not sure what you are talking about. Swift 2.2 simply does not have a `swift build`. Swift build is Swift 3 only.

This is not related to the fact that `swift build` is implemented to a binary called swift-build, but that `swift build` is not available in the first place. In your implementation you DO make swift-build available to Swift 2.2 versions (which then silently does nothing.

**Comment by kylef** [comment]
What I was saying is that the `swift-build` binary itself is an implementation detail. Users are expected to run `swift build` and not know that `swift-build` exists (I'd expect). Relying on these implementation details tightly couples your script to how swift-build is implemented, if the implementation changes in the future the script may also break.

Running `swift foo` and `swift build` against Swift 2.2 produce the same errors. If an executable is found in the `PATH` named `swift-something` `something` will be available as a subcommand.

```shell
$ swift foo
error: unable to invoke subcommand: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-foo (No such file or directory)

$ swift build
error: unable to invoke subcommand: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build (No such file or directory)
```

As a short term solution, you could instead run `swift build --version` or `swift build --help` and check for the 0 / 127 (command not found / illegal_command) exit code.

```shell
#!/usr/bin/env bash

$(swift build --version >/dev/null 2>/dev/null)
if [ $? != 127 ]; then
  echo "swift build is available"
else
  echo "swift build is not available"
fi
```

```shell
$ swiftenv local 2.2
$ ./test.sh
swift build is not available
$ swiftenv local 3.0
$ ./test.sh
swift build is available
```

**Comment by helje5** [comment]
Please be so nice to actually read my original bug report ;-) In which I was seeing this:

    $ swiftenv local 2.2
    $ ./test.sh
    swift build is not available
    $ swiftenv local 3.0
    swift build is available
    $ swiftenv local 2.2
    $ ./test.sh
    swift build is available

This is because the switch to Swift 3 installs the swift-build shim which is then picked up by Swift 2.2.

**Comment by kylef** [comment]
@helje5 I think perhaps we are both running a different version of swiftenv at the time which could have produced a different result.

Could you test this on swiftenv 1.2.1?

**Comment by helje5** [comment]
Doesn't matter anymore, 3.0 is now the stable version. Sounds like your code is properly deleting shims now? Hence just closing this.
