### ISSUE TITLE
How to install the 3.0 previews?

### ISSUE THREAD

**Issue by Dev1an** [kylef/swiftenv#40]
When I try to `swiftenv install 3.0-preview-1` I get
```
We don't have build instructions for 3.0-preview-1
```

**Comment by CharlesHarroch** [comment]
I've the same question. Do you have an answer now ?

**Comment by kylef** [comment]
This appears to be a bug on our side. You can force installing from binary releases with the `--no-build` flag.

So the following would work:

```shell
$ swiftenv install --no-build 3.0-preview-1
```

**NOTE:** *There is no 3.0-preview-1 for macOS, only Linux. If you're running macOS you will instead need to install Xcode 8 beta 1 to get the Swift preview.*

**Comment by CharlesHarroch** [comment]
Ok thanks ! I try this !

**Comment by CharlesHarroch** [comment]
I've the same error :

> Cloning into 'swiftenv'...
remote: -----> Installing 3.0-preview-1
remote: 3.0-preview-1 was not found on swift.org.
remote:   https://swift.org/builds/swift-3.0-preview-1-release/ubuntu1404/swift-3.0-preview-1-RELEASE/swift-3.0-preview-1-RELEASE-ubuntu14.04.tar.gz
