### ISSUE TITLE
Bad error

### ISSUE THREAD

**Issue by simonnarang** [kylef/swiftenv#43]
I am trying to do stuff using the swift command line tools(e.g. `swift build` or `swift package generate-xcodeproj`) but i get the error `/Users/Si/.swiftenv/shims/swift: line 3: /usr/local/Cellar/swiftenv/1.0.1/libexec/../libexec/swiftenv: No such file or directory`

**Comment by kylef** [comment]
Could you plese run `swiftenv rehash` and check it the problem persists.

**Comment by simonnarang** [comment]
no i just deleted the shims folder and reinstalled... now it works 😜
Thanks though!
