### ISSUE TITLE
Selecting 3.0 when Xcode-beta is installed doesn't work

### ISSUE THREAD

**Issue by explicitcall** [kylef/swiftenv#44]
Hi,

I've installed `swiftenv` with homebrew. I have both Xcode 7.3.1 and Xcode 8 beta 1 installed. Output of `swiftenv versions` follows:

```
% swiftenv versions
* system
  2.2-SNAPSHOT-2016-02-08-a
  2.2
  3.0
```

After I've executed `swift local 3.0` for my project  `swift build` prints this:

```
error: system(["/Users/user/Documents/MySwiftProject/swiftc",
"--driver-mode=swift", "-I", 
"/Users/user/Documents/lib/swift/pm", "-L", "/Users/user/Documents/lib/swift/pm",
"-lPackageDescription", "-target", "x86_64-apple-macosx10.10", 
"/Users/user/Documents/MySwiftProject/Package.swift", 
"-fileno", "4"], posix_spawn error: No such file or directory (2), 
`["/Users/user/Documents/MySwiftProject/swiftc", 
"--driver-mode=swift", "-I", "/Users/user/Documents/lib/swift/pm", "-L", 
"/Users/user/Documents/lib/swift/pm", "-lPackageDescription",
"-target", "x86_64-apple-macosx10.10", 
"/Users/user/Documents/MySwiftProject/Package.swift", "-fileno", "4"]`)
```

Is there any easy way to diagnose this further or fix?

Thanks.

**Comment by kylef** [comment]
That's really bizarre, do you have the same behaviour with other projects?

**Comment by explicitcall** [comment]
Yes, it's stably reproducible for me. The only thing that helped was switching the toolchain in Xcode 8 beta UI and running `xcode-select --switch /Applications/Xcode-beta.app/Contents/Developer`.

**Comment by kylef** [comment]
Okay I'll take a look into this. I think #42 might already be the way to solve this.
