### ISSUE TITLE
Individual user cannot install a snapshot that root already installed

### ISSUE THREAD

**Issue by iachievedit** [kylef/swiftenv#45]
While using `swiftenv` as `root` it downloaded  `swiftenv-DEVELOPMENT-SNAPSHOT-2016-05-31-a` to `/tmp`, thus setting permissions to `root` only.  

Later as a regular system user I tried installing the same snapshot for that user, and was greeted with:

```
tar: swift-DEVELOPMENT-SNAPSHOT-2016-05-31-a-ubuntu15.10/usr/include/lldb/Interpreter/OptionValueChar.h: Cannot open: No such file or directory
```

Perhaps `swiftenv` should create a user-specific directory in `/tmp` when extracting the snapshot .tgz?

**Comment by kylef** [comment]
Since bdbf278 we will now attach the username to the tmp directory to prevent this issue, we will also delete any temporary files (unless `--no-clean` is supplied) after install.

Thanks for reporting @iachievedit.
