### ISSUE TITLE
Fail to install `3.0-preview-2` on linux

### ISSUE THREAD

**Issue by norio-nomura** [kylef/swiftenv#46]
install script on travis-ci:
```
$ eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
```
.swift-version:
```
3.0-preview-2
```
error message:
```console
3.0-preview-2 was not found on swift.org.
  https://swift.org/builds/swift-3.0-preview-2-release/ubuntu1404/swift-3.0-preview-2-RELEASE/swift-3.0-preview-2-RELEASE-ubuntu14.04.tar.gz
```
https://travis-ci.org/Quick/Nimble/jobs/143823099

**Comment by kylef** [comment]
Seems there is some case inconsistency between the preview versions.

- 3.0-preview-1
- 3.0-PREVIEW-2

Does installing `3.0-PREVIEW-2` work?

**Comment by ikesyo** [comment]
I have an instant fix for the issue: https://github.com/ikesyo/swiftenv/commit/2be5a6e71ec92d273f2774cbcfd1e6ce9e6e328a

**Comment by ikesyo** [comment]
The problem is that the generated URL contains invalid `-release` suffixes for preview binaries.
