### ISSUE TITLE
Support installing from swiftnightly.com

### ISSUE THREAD

**Issue by czechboy0** [kylef/swiftenv#49]
There's a great way to get nightly swift builds at http://swiftnightly.com - I'd *love* to see support from installing from it in swiftenv. In particular, I have two stages of support in mind.

(1) User can just copy the remote url and install with `swiftenv install URL`, however currently that doesn't work due to the nightlies being packaged in `.tar.gz` instead of the expected `.pkg`, so you get 

```
➜  ~ swiftenv install https://s3.ap-south-1.amazonaws.com/swiftsnapshots/swift-DEVELOPMENT-SNAPSHOT-2016-07-16-a-osx.tar.gz
https://s3.ap-south-1.amazonaws.com/swiftsnapshots/swift-DEVELOPMENT-SNAPSHOT-2016-07-16-a-osx.tar.gz does not end in '-osx.pkg' as expected.
```

(2) Swiftenv could support the keyword `nightly` (or similar) which would automatically pull the latest published nightly from swiftnightly.com, so the URL copying wouldn't even be necessary.

(1) is a blocker at the moment, (2) would be a nice-to-have.

Thanks for considering!

**Comment by aciidb0mb3r** [comment]
I can open an endpoint to output links in JSON format if it can help for (2)

**Comment by kylef** [comment]
I'm happy to support downloading arbitrary URLs of Swift toolchains or Swift tarballs. However, I do not want to encourage installing untrusted third-party binaries and therefore am not interested in adding dedicated support for swiftnightly.

If you'd like to, you're more than welcome to develop a plugin, you can add a command to PATH such as `swiftenv-nightlies` which will allow you to view a list of versions and/or download these.

---

That said, it does seem that these tarballs are actually some form of broken `Xcode.app` which have the toolchains inside. 

```shell
$ tar tvf swift-DEVELOPMENT-SNAPSHOT-2016-07-16-a-osx.tar.gz | head -n1
drwxr-xr-x  0 buildnode staff       0 17 Jul 10:34 Applications/Xcode.app/Contents/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-07-16-a.xctoolchain/
```

I don't want to add additional complexity to swiftenv to handle installing, managing and uninstalling macOS specific applications. swiftenv doesn't handle installing ordinary Xcode applications either, that a task better left for [xcode-install](https://github.com/neonichu/xcode-install) install to solve.

Going forward these are the formats that we will support in swiftenv:

- A tarball including the Swift version (i.e, the `usr/` directory). The format that is used currently by Apple for their Linux tarballs. This format is not OS specific.
- Swift toolchain packages (`.pkg`). A package can install the toolchains to `/Library/Developer/Toolchains` or `~/Library/Developer/Toolchains`. This format is macOS specific.

**Comment by czechboy0** [comment]
Thanks for the thorough reply, @kylef!

Regarding the strange format of the toolchains, I wasn't aware of that (I just assumed they were identical to the swift.org ones). I'm sure it's something we can look into separately so that we *do* end up with nightlies in the identical format to the Apple-distributed toolchains.

When it comes to the untrusted sources, I absolutely appreciate you not wanting to encourage downloading from untrusted sources.

But as far as I can tell, currently we're not checking the PGP signature of downloaded toolchains (from Swift.org) anyway, are we? I guess that could be a separate ticket, where if we added that, we don't have to trust as much *where we get the toolchain from* as much as what's inside of it - testified by the matching signature (in Apple's case).

Considering we do add that, hopefully we could design it in a way that allows for more key sources to be added - thus swiftnightlies could have its own PGP keys which sign the toolchains. This could be added in a manifest file somewhere in `~/.swiftenv`, where the Apple keys would be present by default.

I believe that would both add security (comparing to today) and the ability to install from other sources, without putting unexperienced user in risk (my thought is that if you don't manually add the key sources, installation from other sources will fail).

I understand that might be a considerable amount of work, but it might provide most benefits and security long term. What do you think?

**Comment by czechboy0** [comment]
Just FYI, swiftnightly is now served over HTTPS and has a JSON API: https://swiftnightly.com/api.php

**Comment by czechboy0** [comment]
In the light of the swift team releasing snapshots frequently enough, I'm not sure this needs attention anymore. Closing.
