### ISSUE TITLE
A Full & Proper Uninstall

### ISSUE THREAD

**Issue by eligreg** [kylef/swiftenv#50]
Would you please outline a full and proper uninstall that fully removes swiftenv & reverts to the system default Swift?

I used homebrew for the installation.

Seemingly I would follow these steps:

1. Remove from my `.bash_profile` the line
`'if which swiftenv > /dev/null; then eval "$(swiftenv init -)"; fi'`

2. Uninstall using Homebrew
`$brew uninstall swiftenv`

What I struggle with is how to properly set the path back to the system Swift.

(I'm no sysadmin!) Thanks in advance.

**Comment by kylef** [comment]
That's pretty much all you need to do, you would also want to delete the `~/.swiftenv` directory and remember to relaunch your shells for the new `.bash_profile` to take effect.

1) Remove swiftenv from any `.bash_profile`, `.bashrc`, `.zshenv`, `fish.config` that you've added during installation.
2) Remove `SWIFTENV_ROOT` aka, `~/.swiftenv`.

  ```shell
  $ rm -fr ~/.swiftenv
  ```

3) Uninstall any swiftenv packages (brew uninstall, pacman, etc).

**Comment by kylef** [comment]
If you still want to use swiftenv and want to switch to the system Swift version, you can set the swift version to `system` to do this with swiftenv.

```shell
# Sets the global swift version
$ swiftenv global system

# Sets the local swift version (in current directory)
$ swiftenv local system
```

**Comment by eligreg** [comment]
Great answers, thank you.

**Comment by t3ndai** [comment]
@kylef thanks
