### ISSUE TITLE
Update API for Swift 3 Release

### ISSUE THREAD

**Issue by edjiang** [kylef/swiftenv#56]
```
edjiang@ubuntu:~$ swiftenv install 3.0
We don't have build instructions for 3.0.
```

**Comment by Danappelxx** [comment]
I haven't tested it but the correct tag is actually `swift-3.0-RELEASE`.

**Comment by edjiang** [comment]
Swiftenv usually uses the raw numbers for actual release builds. 

But anyways:

```
edjiang@ubuntu:~$ swiftenv install swift-3.0-RELEASE
We don't have build instructions for 3.0-RELEASE.
```

**Comment by Danappelxx** [comment]
Fair enough :)

**Comment by edjiang** [comment]
```
edjiang@ubuntu:~$ swiftenv install --list
2.2-dev
2.2
2.2.1
3.0-dev
```

Swiftenv seems to pull the versions from Kyle's API:

https://swiftenv-api.fuller.li/versions

```json
{
  "_embedded": {
    "3.0-GM-CANDIDATE": {
      "_links": {
        "self": {
          "href": "/versions/3.0-GM-CANDIDATE"
        }
      }
    },
    "2.2": {
      "_links": {
        "self": {
          "href": "/versions/2.2"
        }
      }
    },
    "3.0-PREVIEW-1": {
      "_links": {
        "self": {
          "href": "/versions/3.0-PREVIEW-1"
        }
      }
    },
    "3.0-PREVIEW-5": {
      "_links": {
        "self": {
          "href": "/versions/3.0-PREVIEW-5"
        }
      }
    },
    "3.0-PREVIEW-3": {
      "_links": {
        "self": {
          "href": "/versions/3.0-PREVIEW-3"
        }
      }
    },
    "3.0-PREVIEW-2": {
      "_links": {
        "self": {
          "href": "/versions/3.0-PREVIEW-2"
        }
      }
    },
    "3.0-PREVIEW-6": {
      "_links": {
        "self": {
          "href": "/versions/3.0-PREVIEW-6"
        }
      }
    },
    "3.0-PREVIEW-4": {
      "_links": {
        "self": {
          "href": "/versions/3.0-PREVIEW-4"
        }
      }
    },
    "2.2.1": {
      "_links": {
        "self": {
          "href": "/versions/2.2.1"
        }
      }
    }
  },
  "_links": {
    "self": {
      "href": "/versions"
    }
  }
}
```

**Comment by paulofaria** [comment]
Yeah! Just found that out while trying to send a patch. This call returns 404 and then everything fails:

https://swiftenv-api.fuller.li/versions/3.0/binaries/ubuntu14.04

What's the rationale for this? Why can't we try swift.org directly?

I'll try to send a patch to https://github.com/kylef/swiftenv-api

**Comment by paulofaria** [comment]
Created a PR here: 

https://github.com/kylef/swiftenv-api/pull/6

I imagine this is the only thing needed? @kylef  ☺️

**Comment by ikesyo** [comment]
https://github.com/kylef/swiftenv-api/pull/6 is merged now. 😉

**Comment by edjiang** [comment]
Does it take time to redeploy?

```
edjiang@ubuntu:~$ swiftenv install --list
2.2-dev
2.2
2.2.1
3.0-dev
edjiang@ubuntu:~$ swiftenv install 3.0
We don't have build instructions for 3.0.
```

**Comment by ikesyo** [comment]
Are you using Ubuntu or macOS? If the latter, Swift 3.0 is a part of Xcode 8 and there is no Swift installer package for the release.

**Comment by edjiang** [comment]
Looks like it's working on ubuntu 14.04, but not 15.10 for me

**Comment by kylef** [comment]
If you are on a platform where there are binary versions of Swift, swiftenv will install the Apple provided binary images:

```shell
$ swiftenv install 3.0
Downloading https://swift.org/builds/swift-3.0-release/ubuntu1510/swift-3.0-RELEASE/swift-3.0-RELEASE-ubuntu15.10.tar.gz
3.0 has been installed.
```

There are only binaries for:

- ubuntu1510
- ubuntu1404

If you are running macOS, you will need to install Xcode. Apple has not provided a `3.0` binary toolchain for macOS like they did for the `3.0` GM.

If there isn't a binary image, swiftenv will then use the [profiles included in swiftenv](https://github.com/kylef/swiftenv/tree/master/share/swiftenv-build) to install from source, if a profile for the version exists.

swiftenv does not have a `3.0` build profile. I'm waiting for all of the source repositories to be tagged with `3.0` before this profile can be created.

##### Repositories missing `swift-3.0-RELEASE` tags:

- [x] https://github.com/apple/swift/releases/tag/swift-3.0-RELEASE
- [ ] https://github.com/apple/swift-llvm/releases
- [ ] https://github.com/apple/swift-package-manager/releases
- [ ] https://github.com/apple/swift-llbuild/releases
- [ ] https://github.com/apple/swift-corelibs-xctest/releases
- [ ] https://github.com/apple/swift-corelibs-libdispatch/releases
- [ ] https://github.com/apple/swift-corelibs-foundation/releases
- [ ] https://github.com/apple/swift-cmark/releases
- [x] https://github.com/apple/swift-lldb/releases/tag/swift-3.0-RELEASE
- [ ] https://github.com/apple/swift-clang/releases

At the moment, you can install the `3.0-dev` profile in swiftenv (`swiftenv install 3.0-dev`) to build 3.0 from source using the 3.0/stable branches.

---

> What's the rationale for this? Why can't we try swift.org directly?

@paulofaria swiftenv used to hit swift.org directly. But time after time the Swift team changed the URI format for the Swift versions thus breaking swiftenv. These URL formats were too unstable to use in a released command line tool (https://github.com/kylef/swiftenv/issues/10). I don't want to have to handle additional cases and make a release every time Apple decides to slightly change the URI format. Especially when the new URI formats only apply to versions going forward and the old versions still retain the old format, this means we eventually build ranges of versions using one URI format.

Having an API which has all of these URLs (version controlled with audit logs) greatly simplifies swiftenv. Currently adding versions is done manually so we can review the URLs are correct before promoting to production. Now this has stabilised I plan to automate updating the versions in the swiftenv API so they will become available much sooner after a release of Swift automatically.

**Comment by edjiang** [comment]
I understand that, but it's not working on 15.10 for me.

Try this in Docker:

Ubuntu 15.10:

```
root@ubuntu:/home/edjiang/throwaway-code/DockerSwift# cat Dockerfile
FROM ubuntu:15.10
RUN apt-get update
RUN apt-get -qy install clang libicu-dev build-essential git libcurl4-openssl-dev libxml2 curl
RUN git clone https://github.com/kylef/swiftenv.git /usr/local/swiftenv
ENV SWIFTENV_ROOT /usr/local/swiftenv
ENV PATH $SWIFTENV_ROOT/bin:$SWIFTENV_ROOT/shims:$PATH
RUN swiftenv install 3.0
root@ubuntu:/home/edjiang/throwaway-code/DockerSwift# docker build .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM ubuntu:15.10
 ---> 9b9cb95443b5
Step 2 : RUN apt-get update
 ---> Using cache
 ---> cf74997a343c
Step 3 : RUN apt-get -qy install clang libicu-dev build-essential git libcurl4-openssl-dev libxml2 curl
 ---> Using cache
 ---> e60478cea24d
Step 4 : RUN git clone https://github.com/kylef/swiftenv.git /usr/local/swiftenv
 ---> Using cache
 ---> 0a2f252f3962
Step 5 : ENV SWIFTENV_ROOT /usr/local/swiftenv
 ---> Using cache
 ---> c2f201efb198
Step 6 : ENV PATH $SWIFTENV_ROOT/bin:$SWIFTENV_ROOT/shims:$PATH
 ---> Using cache
 ---> d70468b34575
Step 7 : RUN swiftenv install 3.0
 ---> Running in 954003953b04
We don't have build instructions for 3.0.
The command '/bin/sh -c swiftenv install 3.0' returned a non-zero code: 1
```

On 14.04:

```
root@ubuntu:/home/edjiang/throwaway-code/DockerSwift# cat Dockerfile
FROM ubuntu:14.04
RUN apt-get update
RUN apt-get -qy install clang libicu-dev build-essential git libcurl4-openssl-dev libxml2 curl
RUN git clone https://github.com/kylef/swiftenv.git /usr/local/swiftenv
ENV SWIFTENV_ROOT /usr/local/swiftenv
ENV PATH $SWIFTENV_ROOT/bin:$SWIFTENV_ROOT/shims:$PATH
RUN swiftenv install 3.0
root@ubuntu:/home/edjiang/throwaway-code/DockerSwift# docker build .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM ubuntu:14.04
 ---> 4a725d3b3b1c
Step 2 : RUN apt-get update
 ---> Using cache
 ---> eaccd91b3832
Step 3 : RUN apt-get -qy install clang libicu-dev build-essential git libcurl4-openssl-dev libxml2 curl
 ---> Using cache
 ---> 71cc50b104ab
Step 4 : RUN git clone https://github.com/kylef/swiftenv.git /usr/local/swiftenv
 ---> Using cache
 ---> a5db8c30a562
Step 5 : ENV SWIFTENV_ROOT /usr/local/swiftenv
 ---> Using cache
 ---> 5df9a22f9d6e
Step 6 : ENV PATH $SWIFTENV_ROOT/bin:$SWIFTENV_ROOT/shims:$PATH
 ---> Using cache
 ---> bdce1d75aa65
Step 7 : RUN swiftenv install 3.0
 ---> Running in 46a3eb244f79
Downloading https://swift.org/builds/swift-3.0-release/ubuntu1404/swift-3.0-RELEASE/swift-3.0-RELEASE-ubuntu14.04.tar.gz
```

**Comment by Danappelxx** [comment]
>If you are running macOS, you will need to install Xcode. Apple has not provided a 3.0 binary toolchain for macOS like they did for the 3.0 GM.

Looks like they added it? Made a pr kylef/swiftenv-api#8

**Comment by kylef** [comment]
@edjiang The Ubuntu 15.10 image doesn't include lsb_release which the 14.04 image had. `lsb-release` is the standard tool that can be used to detect the distro/distro version and is normally included on all Ubuntu installations. Swiftenv attempts to use `lsb_release` to figure out your platform, if it isn't there it cannot find the platform.

You can add `apt-get install lsb-release` to your Dockerfile to fix this problem.

#### swiftenv docker image

I'd like to mention there is a `swiftenv` Docker image which uses Ubuntu 15.10 and installs swiftenv on top. Check out https://hub.docker.com/r/kylef/swiftenv/ for more information.

```
FROM kylef/swiftenv
RUN swiftenv install 3.0
```

**Comment by edjiang** [comment]
Gotcha. I was trying to show you how to reproduce with Docker, but when I added lsb-release to my Dockerfile, it now works =] 

I guess I have a different problem, then. My main box is on 16.04 and usually could use Swiftenv to install, with the override environment variable:

`UBUNTU_VERSION=15.10 swiftenv install 3.0`

It has been working with all of the development snapshots, but unfortunately not the release version of Swift. Any idea why? 

```
edjiang@ubuntu:~$ swiftenv install DEVELOPMENT-SNAPSHOT-2016-09-10-a
Apple does not provide binary releases for ubuntu16.04.

You may manually install Swift and place it into:
  /home/edjiang/.swiftenv/versions/DEVELOPMENT-SNAPSHOT-2016-09-10-a

Alternatively, you can force using a Ubuntu binaries by using the following:
  $ env UBUNTU_VERSION=ubuntu15.10 swiftenv install DEVELOPMENT-SNAPSHOT-2016-09-10-a

edjiang@ubuntu:~$ swiftenv install 3.0
We don't have build instructions for 3.0.
```

**Comment by paulofaria** [comment]
@kylef I think that `lsb-release` issue could be mentioned in the README. Would you like me to send a PR?

**Comment by ikesyo** [comment]
@edjiang Looks like adding `--no-build` option would work around the issue.
