### ISSUE TITLE
Strange behavior with Go and linking CGo libraries

### ISSUE THREAD

**Issue by jondot** [kylef/swiftenv#62]
It may not make any sense for swiftenv users, but when evaling swiftenv init, it appears to inject some environment that later conflicts with Go (the programming language), and causes the Go linker to hang indefinitely.

For documentation purposes, here's the Go output.
https://github.com/golang/go/issues/17192

For now I've disabled automatic initialization of swiftenv.

Hopefully this issue helps others.

**Comment by kylef** [comment]
@jondot Could you please share which version of swiftenv you are running. It can be found via `swiftenv --version`.

**Comment by jondot** [comment]
here we go:
```
$ swiftenv --version
swiftenv 1.1.0
```

**Comment by kylef** [comment]
@jondot I have a feeling that https://github.com/kylef/swiftenv/pull/39 would solve this problem. Could you try upgrading to swiftenv 1.2.0 and give it a go.

**Comment by jondot** [comment]
Interesting! I'll try and get back to this issue

**Comment by kylef** [comment]
Pretty sure this is fixed so I'm gonna close. Let's reopen if there is any problems.
