### ISSUE TITLE
Make swiftenv-api endpoint configurable

### ISSUE THREAD

**Issue by robertjpayne** [kylef/swiftenv#63]
Currently the swiftenv-api is a requirement to install Linux builds. The API is down currently and has been down for an hour or more and is preventing our CI from running.

Even if we hosted our own swiftenv-api there is currently no way to configure it. The scripts should allow an environment variable to override the default URL.

**Comment by kylef** [comment]
Unfortunately the API did go down for a few hours. I woke up to an email from Heroku saying I hit the limitations of the free tier and I've upgraded the application so it will continue working (https://github.com/kylef/swiftenv-api/issues/9).

That said, I think it would be better if swiftenv cli tool would include the URLs for stable versions of Swift locally. This means that installing a full release (`3.0`, `2.2.1` etc) will work without the API. The API will be called for unknown releases (i.e, if you have an older version of swiftenv and Swift 3.1 came out), or any of the development snapshot releases. There are too many and they change too often to go into a slower moving tool such as swiftenv.

I will make some changes to swiftenv (on top of #61) which will allow swiftenv to locally store the swift binary URLs in swiftenv itself. We can also add the ability to set an environment variable to override the API used, but I don't think it will be as important as the other changes I've mentioned.

**Comment by robertjpayne** [comment]
@kylef sounds great!
