### ISSUE TITLE
Is there Swift 2.3 version?

### ISSUE THREAD

**Issue by judi0713** [kylef/swiftenv#65]
I am trying to migrate my project from 2.3 to 3.0.
Now I want to install Swift 2.3 version, but when I use
`swiftenv install 2.3`
The error message show
`We don't have build instructions for 2.3.`
Is there any solution?

**Comment by kylef** [comment]
There isn't actually a release of Swift 2.3 (see https://swift.org/download/#releases). There is however a version 2.3 bundled with Xcode 8. But there are no open source releases or tags for 2.3.

I am not sure why this is the case, you would be best off asking on the [Swift mailing list](https://swift.org/community/#mailing-lists) why there is no 2.3 release.

**Comment by judi0713** [comment]
Oh, thank you! I think I misunderstanding Xcode error.
Really sorry to bother you! I will close this issue.
