### ISSUE TITLE
swiftenv install 3.0 fails with "version `3.0' is not installed" on TravisCi's xcode7.2 image

### ISSUE THREAD

**Issue by dgholz** [kylef/swiftenv#68]
I've set up a Travis CI build to install swift 3.0 on their `xcode7.2` image. When I configure it to install 3.0, I see:

```bash
$ swiftenv install --verbose 3.0
Checking for a URL for the 3.0 on osx.
Installing 3.0 from https://swift.org/builds/swift-3.0-release/xcode/swift-3.0-RELEASE/swift-3.0-RELEASE-osx.pkg on osx.
Downloading https://swift.org/builds/swift-3.0-release/xcode/swift-3.0-RELEASE/swift-3.0-RELEASE-osx.pkg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  254M  100  254M    0     0  11.1M      0  0:00:22  0:00:22 --:--:-- 12.5M
installer: Package name is Swift Open Source Xcode Toolchain
installer: Installing at base path /
installer: The install was successful.
3.0 has been installed.
swiftenv: version `3.0' is not installed
```

I think this is because https://github.com/kylef/swiftenv/blob/master/share/swiftenv-install/3.0#L11 will use `https://swift.org/builds/swift-3.0-release/xcode/swift-3.0-RELEASE/swift-3.0-RELEASE-osx.pkg` to install version 3.0. That package installs to `/Library/Developer/Toolchains/swift-3.0-RELEASE.xctoolchain`, but https://github.com/kylef/swiftenv/blob/master/libexec/swiftenv-prefix#L29 instead checks for `/Library/Developer/Toolchains/swift-3.0.xctoolchain` (without the _`-RELEASE`_).

I can't replicated it locally, as I've installed Xcode 8 & `swiftenv-prefix` finds `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift`, and its version is
```
Apple Swift version 3.0 (swiftlang-800.0.46.2 clang-800.0.38)
Target: x86_64-apple-macosx10.9
```
which is recognised by https://github.com/kylef/swiftenv/blob/master/libexec/swiftenv-prefix#L47

**Comment by dgholz** [comment]
[Here's my Travis CI osx job with `xtrace` enabled](https://travis-ci.org/dgholz/Linewise/jobs/164852937), if you want to see what `swiftenv` did.

**Comment by sauliusgrigaitis** [comment]
I get same error on my Ubuntu 16.04:

```
$ swiftenv install 3.0
3.0 has been installed.
swiftenv: version `3.0' is not installed
```

**Comment by kylef** [comment]
@dgholz I've made some changes to check for `-RELEASE` versions in master to solve this problem. Please give it a try again.

I would note that Xcode 8 is a dependency of Swift 3.0. I don't think you will be able to run Swift 3.0 on macOS without Xcode 8. You can see this mentioned on Swift.org https://swift.org/download/#releases

![screen shot 2016-10-11 at 12 52 38](https://cloud.githubusercontent.com/assets/44164/19287963/dd441410-8ffb-11e6-8bb7-d739668f1f4b.png)

---

@sauliusgrigaitis your issue doesn't seem to be the same one as this thread. Can you please file another issue including the version of swiftenv you are using and we can debug this problem you are facing.

**Comment by kylef** [comment]
@sauliusgrigaitis I think https://github.com/kylef/swiftenv/commit/041ac8ab3fc52079e4d82e7de515940c4141fef6 will solve your problem, can you try updating swiftenv from git and test.

**Comment by dgholz** [comment]
@kylef thanks, I now see `3.0` installing & my build proceeds, and that my test fail to run due to Swift 3.0 requiring Xcode8… exactly as you thought.

I switched the `osx_image` to `xcode8`, and I see that `swiftenv install 3.0` short-circuits, but returns non-zero:
```
2.15s$ swiftenv install --verbose 3.0

3.0 is already installed.

The command "swiftenv install --verbose 3.0" failed and exited with 1 during .
```
My expectation is that it should return zero, since `3.0` was installed. Shall I make a separate issue?

**Comment by kylef** [comment]
@dgholz Since you've explicitly tried to install swiftenv it would provide an error if it's already installed. I've added an argument (`-s` or `--skip-existing`) which can be used to exit 0 instead (useful for things like CI).

```shell
$ swiftenv install --skip-existing 3.0
$ swiftenv install -s 3.0
```

If you're using the Travis CI integration, the latest version of it will use `-s` so it won't fail when the Swift version is already installed.

https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh

Does that work for you?

**Comment by wongzigii** [comment]
@kylef I just try your script in my fork. https://github.com/wongzigii/Quick/commit/febded8513102e6558239921a8d2b2bbc3579018 But seems the CI is still in error.

**Comment by kylef** [comment]
@wongzigii Please see the Travis CI integration guide: https://swiftenv.fuller.li/en/latest/integrations/travis-ci.html. The way you have configured swiftenv is with a different/unsupported way by piping it into bash. You will also need to switch to the Travis CI trust image as mentioned in the guide.

**Comment by dgholz** [comment]
@kylef works like a charm, thanks for all your help!
