### ISSUE TITLE
Should there be a swift-ide-test executable? 

### ISSUE THREAD

**Issue by joedaniels29** [kylef/swiftenv#70]
So I'm trying to print the interface to a module. https://bugs.swift.org/browse/SR-2502 says that I should be able to use `swift-ide-test`, though the command is apparently not usually installed. Should this binary be included in shims? or is there a better way to accomplish this? 
thanks!

**Comment by kylef** [comment]
The shims will include every binary in the installed Swift versions `/usr/bin` directory that starts with `swift` or `lldb`. If the tool `swift-ide-test` was found, a shim for it would be generated during `swiftenv rehash`.

I have never seen `swift-ide-test` inside any Swift version I've used so far (haven't kept up with the newer betas). Is this found in a specific version?
