### ISSUE TITLE
Cannot install 3.0.1 on Ubuntu 16.04

### ISSUE THREAD

**Issue by ianpartridge** [kylef/swiftenv#71]
Note: I think this is a different issue from #69 

Swift.org provides prebuilt binaries for Swift 3.0.1 on Ubuntu 16.04 - see https://swift.org/download/

The package is at https://swift.org/builds/swift-3.0.1-release/ubuntu1604/swift-3.0.1-RELEASE/swift-3.0.1-RELEASE-ubuntu16.04.tar.gz

However, I see:

```
$ swiftenv install 3.0.1
We don't have build instructions for 3.0.1.
```

**Comment by ianpartridge** [comment]
`env PLATFORM=ubuntu16.04 swiftenv install 3.0.1` does work. Perhaps this is because I'm using elementaryOS, a derivative of Ubuntu 16.04?

**Comment by kylef** [comment]
I'd assume that elementaryOS have their own name and version numbers. So when swiftenv tries to determine the platform it ends up with elementaryOS.

You can use `lsb_release` to determine the current platform name (on linux where lsb_release is installed):

```shell
$ lsb_release -rs
```

Maybe the best way in this case is to just set `PLATFORM`.

**Comment by ianpartridge** [comment]
Thanks Kyle.

```
$ lsb_release -rs
0.4
```

So yes, I think `PLATFORM=` is the correct workaround.  Thanks!

**Comment by kylef** [comment]
@ianpartridge I don't use this platform myself, but if you think it would be useful to add a note to swiftenv documentation feel free to make a PR.

We have some platform specific notes on building from source at https://swiftenv.fuller.li/en/latest/building-swift.html ([page source](https://github.com/kylef/swiftenv/blob/master/docs/building-swift.md)). We could perhaps introduce a similar document for binary installation.
