### ISSUE TITLE
3.0-dev does not build swift-build on Ubuntu 17.04

### ISSUE THREAD

**Issue by arslan2012** [kylef/swiftenv#77]
XX@XX:~/ClionProjects/Hello Swift$ swiftenv local 3.0-dev 
    XX@XX:~/ClionProjects/Hello Swift$ swift build
    no such command: swift-build
    XX@XX:~/ClionProjects/Hello Swift$ ls /home/XX/.swiftenv/versions/3.0-dev/usr/bin/
    swift  swift-demangle
Does reinstalling helps?

**Comment by sinoru** [comment]
Currently swiftenv-build build swift 3.x correctly. I'm trying to fix it(#76). Meanwhile, you can try https://github.com/sinoru/swiftenv/tree/align-build.
