### ISSUE TITLE
Need option to use SSH to clone repositories

### ISSUE THREAD

**Issue by arslan2012** [kylef/swiftenv#78]
Cloning into 'swift'...
    fatal: unable to access 'https://github.com/apple/swift.git/': Failed to connect to github.com port 443:      Connection timed out

So basicly, it's just nice to have option to use SSH to clone

**Comment by stupergenius** [comment]
Thanks @arslan2012. I see a couple possible issues with this approach, but perhaps you can add some refinements that clarify some behavior:

1. How would you specify which version you wanted to install?
1. How would, once you've built and installed the git branch, switch between versions? This presents a possible resolution error: what if you had installed a version from git, and the *same* version via the existing mechanism. Would you expect to switch only to the git installed version via a tag/commit hash?
1. Can you provide a use case for this that you have?
1. And can I get you to do some legwork? Are there other version managers that provide this kind of functionality, and how (if they do) do they manage the versions installed from git?

**Comment by arslan2012** [comment]
for example

    import PackageDescription

    let package = Package(
        name: "DeckOfPlayingCards",
        targets: [],
        dependencies: [
            .Package(url: "https://github.com/apple/example-package-fisheryates.git",
                 majorVersion: 1),
            .Package(url: "https://github.com/apple/example-package-playingcard.git",
                 majorVersion: 1),
    ]
    )
and

    import PackageDescription

    let package = Package(
        name: "DeckOfPlayingCards",
        targets: [],
        dependencies: [
            .Package(url: "git@github.com:apple/example-package-fisheryates.git",
                 majorVersion: 1),
            .Package(url: "git@github.com:apple/example-package-playingcard.git",
                 majorVersion: 1),
    ]
    )
works exactly same, except they have different git remote.

I want this feature because my http is going through a proxy that can't connect to github.


If you don't want to add this feature I totally understand.I can always find a new way around. just a suggestion.
