### ISSUE TITLE
Question: Using Swift Version Manager in Another Project

### ISSUE THREAD

**Issue by SDGGiesbrecht** [kylef/swiftenv#79]
This is not really an issue, but it’s the best place I can find to communicate.

I’ve started writing [Workspace](https://github.com/SDGGiesbrecht/Workspace#workspace), a project/workflow manager for swift projects. One of its many planned features is automated set‐up of continuous integration, and I’ve used your Swift Version Manager to get the CI working on Linux.

@kylef, I have two questions:

1. Are you satisfied with the credit I’ve given you on the [CI page](https://github.com/SDGGiesbrecht/Workspace/blob/master/Documentation/Continuous%20Integration.md#special-thanks) and on the main [Readme](https://github.com/SDGGiesbrecht/Workspace#what-workspace-can-do)?

2. Is it up‐to‐date, stable, and recommended to install and run via `eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"`?

Thanks for your excellent work.

**Comment by SDGGiesbrecht** [comment]
I am closing this so it no longer clutters my issue list.

@kylef, your thoughts would still be welcome.

**Comment by kylef** [comment]
Hi @SDGGiesbrecht,

1) The credit is great, as long as you leave the [copyright](https://github.com/kylef/swiftenv/blob/master/LICENSE) intact from any distribution of swiftenv as per the license then I'm happy. Nice to see someone building tools on top of swiftenv!

2) That installation method is great for CI, but I would recommend following the [installation instructions](https://swiftenv.fuller.li/en/latest/installation.html) for a full installation. The eval script doesn't perform a full installation and only supports a subset of the shells which are commonly used in CI environments.

**Comment by SDGGiesbrecht** [comment]
Great. Thanks!
