### ISSUE TITLE
Feature swift list

### ISSUE THREAD

**Issue by netbe** [kylef/swiftenv#8]
Couldn't figure out which version I had to install, so maybe a command to list all versions of swift available to install or even a `swift install latest`

**Comment by kylef** [comment]
This is planned (and also tab-completions for versions with `swiftenv install`), but I don't see any need to do this right now as there are no stable versions of Swift. Showing every snapshot will be hard to maintain (have to update swiftenv often, and users need to update to see latest versions which change weekly). This will also result in an awfully long list and be poor for user experience in the long run.

Current builds that Apple provide as binaries (installable via `swiftenv install`):

- 2.2-SNAPSHOT-2016-01-11-a
- 2.2-SNAPSHOT-2016-01-06-a
- 2.2-SNAPSHOT-2015-12-31-a
- 2.2-SNAPSHOT-2015-12-22-a
- 2.2-SNAPSHOT-2015-12-21-a
- 2.2-SNAPSHOT-2015-12-18-a
- 2.2-SNAPSHOT-2015-12-10-a
- 2.2-SNAPSHOT-2015-12-01-a (os x only)
- 2.2-SNAPSHOT-2015-12-01-b (linux only)

There is also the versions installable via Xcode, for example `2.1.1`. These pre-date open-source Swift and can only be used on OS X by installing Xcode.

**Comment by deepumukundan** [comment]
The current tab completion suggestions for swiftenv install seems to be pretty outdated. It shows 
2.2      2.2-dev  2.2.1    3.0-dev
Could this list be updated? I can make the change - just not sure where these suggestions are coming up from.
