### ISSUE TITLE
swiftenv install returns non-zero exit code if correct Swift version is already installed

### ISSUE THREAD

**Issue by youming-lin** [kylef/swiftenv#80]
If system already has the correct Swift version installed, `swiftenv install`-ing it again returns a non-zero error. This can break scripts that uses `set -e` even though it's perfectly fine to continue script execution.

Currently, I have resorted to using `swiftenv local` to test for whether or not the correct Swift version is installed before running `swiftenv install` so I won't trigger the non-zero exit code in the case that it is already installed.

**Comment by kylef** [comment]
Hi @youming-lin, you can provide `--skip-existing` or `-s` to `swiftenv install` so it will return 0 when the version is installed.

The reason for this is that you have explicitly asked to install a version of swift, so if it's already installed it should error. The `-s` flag allows this behaviour if necessary.

**Comment by youming-lin** [comment]
Thanks for the tip. Didn't see it in reference guide so I didn't know this is possible.
