### ISSUE TITLE
Using symlinked toolchain is not working

### ISSUE THREAD

**Issue by rbukovansky** [kylef/swiftenv#81]
Hi,
I've created symlink called `dev.xctoolchain` in /Library/Developer/Toolchains/ on my Mac with target to latest DEV SNAPSHOT. `swiftenv versions` shows `dev` in list of versions, but when I do `swiftenv global dev` I get:
```bash
swiftenv: version `dev' is not installed
```

I tried `swiftenv rehash` as well, but that didn't helped either.

Any suggestion? Thanks.

**Comment by rbukovansky** [comment]
@kylef Any idea, please? Thanks.

**Comment by kylef** [comment]
If you symlink the toolchains in the Toolchains directory you will need to follow the naming convention that Apple use `swift-dev.xctoolchain` etc.

I would recommend you instead create the symlink in the `~/.swiftenv/versions` directory, for example `~/.swiftenv/versions/dev` so it doesn't effect the toolchains. You can follow the steps described at https://github.com/kylef/swiftenv/issues/25#issuecomment-224339521.

**Comment by rbukovansky** [comment]
Aha! Yep, both solutions work.

Thanks.
