### ISSUE TITLE
Discoverability of the docs

### ISSUE THREAD

**Issue by Bouke** [kylef/swiftenv#82]
I've been looking for Travis CI integration information, and it appears that the docs have a great section on them. However on the linked page [Installation][0], those pages are not discoverable. Eventually I discovered them through additional Google searches. Then it becomes apparent that 'Installation' is just a chapter and by clicking "swiftenv" in the upper-left corner shows the other chapters.

Thanks for your work!

[0]: https://swiftenv.fuller.li/en/latest/

**Comment by kylef** [comment]
Hi @Bouke, thanks for the suggestion, I've updated the README in 3c82014 to link to the integrations too. If you have any other suggestions on improving the visibility let me know (or feel free to make a pull request).
