### ISSUE TITLE
[FeatReq] Don't update version when new Swift is installed

### ISSUE THREAD

**Issue by rbukovansky** [kylef/swiftenv#83]
Could we please get a option to not let `swiftenv` update global version when new Swift is installed?

I have set 3.0.2 as my global version, but anytime I install new dev snapshot to test compatibility, this indication of global version is overwritten to that dev snapshot.

And yes, I know I can indicate version with `.swiftversion` file in my project, but still...

Thanks.

**Comment by kylef** [comment]
I agree with you, I was never quite sure what the behaviour should be. The problem with not updating the global version is that some users would run `swiftenv install X` and then when they run `swift --version` would have a different version and could be confused what happened to the version they installed.

What behaviour would you think would be clear for users?

**Comment by rbukovansky** [comment]
What I'm suggesting... Option to `swiftenv install`, something like `-noversionupdate`, so current behavior would be still same, but if needed it can be changed...

**Comment by kylef** [comment]
@rbukovansky I was thinking about this and perhaps we can add `--no-global`. There would be `local` and `global`. The user can use `--local` to set the local `.swift-version` file.

This would add:

- `--local`
- `--no-local`
- `--global`
- `--no-global`

The default behaviour could be `--global` UNLESS `--local` or `--no-global` is also supplied.

**Comment by rbukovansky** [comment]
@kylef Sounds good to me! 👍

**Comment by kylef** [comment]
@rbukovansky I've altered the behaviour in https://github.com/kylef/swiftenv/pull/101. Would you like to check/review it?

I've altered the default value further.

**Comment by rbukovansky** [comment]
Looks good to me! 👍🏻

Richard Bukovanský
richard.bukovansky@gmail.com
________________________________

**Comment by rbukovansky** [comment]
@kylef I have tested this feature thoroughly and it works as expected. You can merge it.
