### ISSUE TITLE
Regularly tag new releases as features and fixes are merged

### ISSUE THREAD

**Issue by youming-lin** [kylef/swiftenv#86]
Can we get a new release for brew?

```
ylin@youming-mbpr:~$ brew upgrade swiftenv
Error: kylef/formulae/swiftenv 1.2.1 already installed
```

1.2.1 is missing all the fixes since Oct 2016 and local caches for >=3.0.2 binaries.

**Comment by kylef** [comment]
https://github.com/kylef/homebrew-formulae/commit/4ca7e1e77efa03bd2c91ddd2d8529435bfe5a33c
