### ISSUE TITLE
High Sierra, XCode 9 - cannot load underlying module for 'XCTest'

### ISSUE THREAD

**Issue by rbukovansky** [kylef/swiftenv#88]
Hi, @kylef, do you know if it's issue with my installation (clean High Sierra, just Xcode 9 beta, command-line tools and development snapshots) or it's `swiftenv` doing, when I try to build any Swift module (`swift build` goes fine, `swift test` fails with `cannot load underlying module for 'XCTest'`

I tried to google it, but all are referencing to do something in Xcode.

Thanks.

**Comment by Bouke** [comment]
Have you selected the correct SDK to build against?

```
xcode-select -s ~/Downloads/Xcode-beta.app/Contents/Developer
```

**Comment by kylef** [comment]
@rbukovansky Are you still facing this problem with the latest Xcode betas?

**Comment by rbukovansky** [comment]
No, not anymore. Thanks.
