### ISSUE TITLE
For Fish: i am facing the bellow issue.

### ISSUE THREAD

**Issue by gyanaprakash** [kylef/swiftenv#93]
echo 'setenv SWIFTENV_ROOT "$HOME/.swiftenv"' >> ~/.config/fish/config.fish
-bash: /Users/macbook/.config/fish/config.fish: No such file or directory

**Comment by kylef** [comment]
This error would indicate you are using bash and not fish? Is that correct?

The error is saying you do not have a fish config, perhaps that is because you are using bash and not fish?
