### ISSUE TITLE
[Fish] `swift` not added to path (setenv: Too many arguments)

### ISSUE THREAD

**Issue by donut** [kylef/swiftenv#96]
The latest version of Fish shell has changed how `setenv` works and the line that adds the shims to the path now results in the error:

> setenv: Too many arguments

In `setenv PATH '/usr/local/bin/swiftenv/shims' $PATH` change `setenv` to `set --global --export` or `set -gx`.

**Comment by kylef** [comment]
This should be working in swiftenv master. Could you please confirm before I make a new release.

**Comment by Gurpartap** [comment]
@kylef The `setenv` -> `set -g -x` change should and did fix the problem. It works as expected when brew installed from --HEAD.

**Comment by kylef** [comment]
I've released swiftenv 1.3.0 including the fixes. https://github.com/kylef/swiftenv/releases/tag/1.3.0
