### ISSUE TITLE
Shared libraries not loading correctly on Linux

### ISSUE THREAD

**Issue by kylefrost** [kylef/swiftenv#97]
Trying to use `swiftenv` with Vapor, I ran into an issue where trying a command like `vapor build` would return `error while loading shared libraries: libswiftCore.so: cannot open shared object file: No such file or directory`. I found in [Perfect-Ubuntu/install.sh](https://github.com/PerfectlySoft/Perfect-Ubuntu/blob/master/install.sh#L42) a fix for this (run as sudo): 
```sh
touch /etc/ld.so.conf.d/swift.conf
echo "/usr/lib/swift/linux" >> /etc/ld.so.conf.d/swift.conf 
ldconfig
```
So I used `/home/kyle/.swiftenv/versions/3.1.1/usr/lib/swift/linux` (3.1.1 because that's the current global version I'm using) in place of `/usr/lib/swift/linux` and all now works well. Wasn't sure if you wanted to incorporate this fix into your install scripts.
  
Unrelated P.S. - Nice name/initials.

**Comment by kylef** [comment]
@kylefrost Are you able to produce the same problem with `swift build`?

I'm trying to understand if this is a problem specifically with something that Vapor is doing, or if there is a problem in swiftenv with the swift compiler not finding the dynamic libraries relative to itself.
