### ISSUE TITLE
Doesn't seem to work with Swift 4

### ISSUE THREAD

**Issue by swiftthesorrow** [kylef/swiftenv#98]
I'm on Sierra, 10.12.6.
I ran `swiftenv install 4.0` and then `swiftenv global 4.0`.
`swiftenv global` showed the global version was 4.0, but `swift --version` still showed 3.1.
Could it be I was doing something wrong?

**Comment by swiftthesorrow** [comment]
@kylef I'm using bash.
`$ which swift` outputs `/usr/bin/swift`.
I'll probably try to re-install swiftenv, which, by the way, was installed with brew.

**Comment by swiftthesorrow** [comment]
@kylef 
Okay, I've repeated all steps and even see a .swift-version file, where the version number is set to 4.0. But I still have the same problem.

**Comment by kylef** [comment]
@swiftthesorrow To double check, you added the `swiftenv init` line to your `~/.bashrc` configuration and opened a new shell?

You can confirm if there is a problem with the initialisation by entering `eval "$(swiftenv init -)` into your terminal and then testing what version of Swift is active (`swift --version`).

**Comment by swiftthesorrow** [comment]
@kylef checked .bashrc file as you say and the output for swift version check is:
```
Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42)
Target: x86_64-apple-macosx10.9

```

**Comment by kylef** [comment]
@swiftthesorrow Could you run all of the below commands in the same shell in order and share the complete output please.

```shell
$ eval "$(swiftenv init -)"
$ which swift
$ swiftenv rehash
$ which swift
$ swift --version
$ echo $PATH
```

**Comment by kylef** [comment]
Okay, so that response indicates that the shims are correctly installed and seems that swiftenv is selecting the wrong version of Swift.

Could you run `swiftenv version`, this should show you which version of Swift that swiftenv has selected and why.

**Comment by swiftthesorrow** [comment]
Sure, the output is:
`swiftenv 1.3.0
`

**Comment by kylef** [comment]
I think you've ran `swiftenv --version` not `swiftenv version`. Could you please try again?

**Comment by kylef** [comment]
Also, `swiftenv global 4.0` should set Swift 4.0 as default version.

**Comment by swiftthesorrow** [comment]
@kylef yes, it should but it doesn't :)
`swiftenv version`
output:
`system (set by /Users/swiftthesorrow/.swiftenv/version)`

**Comment by kylef** [comment]
Awesome

**Comment by MasterSwift** [comment]
i have a swift 3.1 running on a linux server. will 

$ swiftenv global 4.0

update it by itself?

**Comment by kylef** [comment]
@MasterSwift You will need to install it first, `swiftenv install 4.0`.
