### ISSUE TITLE
[Question] Running Swift 4.0 Development Snapshot on Linux with Travis CI

### ISSUE THREAD

**Issue by SD10** [kylef/swiftenv#99]
Hey, thanks for the project 😃!
I'm having a bit of trouble getting a Swift 4.0 DEVELOPMENT snapshot running on Linux for TravisCI. 

The error I'm running into is:
![screen shot 2017-09-06 at 9 35 01 pm](https://user-images.githubusercontent.com/7445580/30143447-6e6e12c6-934b-11e7-8e32-efcb56ccacff.png)

You can see the full build log at the failing PR here:
https://github.com/danger/danger-swift/pull/22

If anyone can help me troubleshoot this issue it would be greatly appreciated

**Comment by kylef** [comment]
I am not sure, perhaps it be because you are missing the `LinuxMain.swift` find inside the `Tests/` directory?

**Comment by kylef** [comment]
also, it seems this is a Swift 3 project while you're installing a 4.0 DEV snapshot (https://github.com/danger/danger-swift/blob/master/Package.swift#L18).

**Comment by orta** [comment]
Thanks @kylef - we were missing the linux main - yeah, and it looks like that was it, for future googlers:

```sh
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"

  - swiftenv install https://swift.org/builds/swift-4.0-branch/ubuntu1404/swift-4.0-DEVELOPMENT-SNAPSHOT-2017-09-07-a/swift-4.0-DEVELOPMENT-SNAPSHOT-2017-09-07-a-ubuntu14.04.tar.gz
  - swift build 
  - swift test
```

Got it working.

**Comment by SD10** [comment]
Thank you for clearing this up 👍
